from nose.tools import assert_equal
from parameterized import parameterized
import unittest
from scripts.data_augmentation.augment import doc_to_text
from scripts.data_augmentation.ud_augment import DataAugmentation

class TestUDAugment(unittest.TestCase):
    @parameterized.expand([
        ["TP",
         [{'id': (1,), 'text': 'У', 'lemma': 'у', 'upos': 'ADP', 'xpos': 'Spsl', 'feats': 'Case=Loc', 'head': 2,
           'deprel': 'case', 'deps': '2:case', 'misc': 'Id=0003|LTranslit=u|Translit=U'},
          {'id': (2,), 'text': 'домі', 'lemma': 'дім', 'upos': 'NOUN', 'xpos': 'Ncmsln',
           'feats': 'Animacy=Inan|Case=Loc|Gender=Masc|Number=Sing', 'head': 6, 'deprel': 'obl', 'deps': '6:obl',
           'misc': 'Id=0004|LTranslit=dim|Translit=domi'},
          {'id': (3,), 'text': 'римського', 'lemma': 'римський', 'upos': 'ADJ', 'xpos': 'Ao-msgf',
           'feats': 'Case=Gen|Gender=Masc|Number=Sing', 'head': 4, 'deprel': 'amod', 'deps': '4:amod',
           'misc': 'Id=0005|LTranslit=rymśkyj|Translit=rymśkoho'},
          {'id': (4,), 'text': 'патриція', 'lemma': 'патрицій', 'upos': 'NOUN', 'xpos': 'Ncmsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing', 'head': 2, 'deprel': 'nmod', 'deps': '2:nmod',
           'misc': 'Id=0006|LTranslit=patrycij|Translit=patrycija'},
          {'id': (5,), 'text': 'Руфіна', 'lemma': 'Руфін', 'upos': 'PROPN', 'xpos': 'Npmsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Giv|Number=Sing', 'head': 4, 'deprel': 'flat:title',
           'deps': '4:flat:title', 'misc': 'Id=0007|LTranslit=Rufin|Translit=Rufina'},
          {'id': (6,), 'text': 'була', 'lemma': 'бути', 'upos': 'VERB', 'xpos': 'Vapis-sf',
           'feats': 'Aspect=Imp|Gender=Fem|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
           'deps': '0:root', 'misc': 'Id=0008|LTranslit=buty|Translit=bula'},
          {'id': (7,), 'text': 'прегарна', 'lemma': 'прегарний', 'upos': 'ADJ', 'xpos': 'Ao-fsns',
           'feats': 'Case=Nom|Gender=Fem|Number=Sing', 'head': 8, 'deprel': 'amod', 'deps': '8:amod',
           'misc': 'Id=0009|LTranslit=preharnyj|Translit=preharna'},
          {'id': (8,), 'text': 'фреска', 'lemma': 'фреска', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
           'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 6, 'deprel': 'nsubj', 'deps': '6:nsubj',
           'misc': 'Id=000a|LTranslit=freska|SpaceAfter=No|Translit=freska'},
          {'id': (9,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 10, 'deprel': 'punct',
           'deps': '10:punct', 'misc': 'Id=000b|LTranslit=,|Translit=,'},
          {'id': (10,), 'text': 'зображення', 'lemma': 'зображення', 'upos': 'NOUN', 'xpos': 'Ncnsnn',
           'feats': 'Animacy=Inan|Case=Nom|Gender=Neut|Number=Sing', 'head': 8, 'deprel': 'appos', 'deps': '8:appos',
           'misc': 'Id=000c|LTranslit=zobraženńа|Translit=zobraženńа'},
          {'id': (11,), 'text': 'Венери', 'lemma': 'Венера', 'upos': 'PROPN', 'xpos': 'Npfsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Fem|NameType=Giv|Number=Sing', 'head': 10, 'deprel': 'nmod',
           'deps': '10:nmod', 'misc': 'Id=000d|LTranslit=Venera|Translit=Venery'},
          {'id': (12,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 13, 'deprel': 'cc',
           'deps': '13:cc', 'misc': 'Id=000e|LTranslit=ta|Translit=ta'},
          {'id': (13,), 'text': 'Адоніса', 'lemma': 'Адоніс', 'upos': 'PROPN', 'xpos': 'Npmsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Giv|Number=Sing', 'head': 11, 'deprel': 'conj',
           'deps': '10:nmod|11:conj', 'misc': 'Id=000f|LTranslit=Adonis|SpaceAfter=No|Translit=Adonisa'},
          {'id': (14,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 6, 'deprel': 'punct',
           'deps': '6:punct', 'misc': 'Id=000g|LTranslit=.|Translit=.'}],
         ["У домі патриція римського Руфіна була фреска прегарна, зображення Венери та Адоніса."]],
        ["TP",
         [{'id': (1,), 'text': 'Це', 'lemma': 'це', 'upos': 'PRON', 'xpos': 'Pd--nnsnn',
           'feats': 'Animacy=Inan|Case=Nom|Gender=Neut|Number=Sing|PronType=Dem', 'head': 2, 'deprel': 'nsubj',
           'deps': '2:nsubj', 'misc': 'Id=001j|LTranslit=ce|Translit=Ce'},
          {'id': (2,), 'text': 'одна', 'lemma': 'один', 'upos': 'DET', 'xpos': 'Pi--f-sna',
           'feats': 'Case=Nom|Gender=Fem|Number=Sing|PronType=Ind', 'head': 0, 'deprel': 'root', 'deps': '0:root',
           'misc': 'Id=001k|LTranslit=odyn|Promoted=Yes|Translit=odna'},
          {'id': (3,), 'text': 'з', 'lemma': 'з', 'upos': 'ADP', 'xpos': 'Spsg', 'feats': 'Case=Gen', 'head': 6,
           'deprel': 'case', 'deps': '6:case', 'misc': 'Id=001l|LTranslit=z|Translit=z'},
          {'id': (4,), 'text': 'надзвичайно', 'lemma': 'надзвичайно', 'upos': 'ADV', 'xpos': 'R', 'head': 5,
           'deprel': 'advmod', 'deps': '5:advmod', 'misc': 'Id=001m|LTranslit=nadzvyčajno|Translit=nadzvyčajno'},
          {'id': (5,), 'text': 'важливих', 'lemma': 'важливий', 'upos': 'ADJ', 'xpos': 'Afp-pgf',
           'feats': 'Case=Gen|Degree=Pos|Number=Plur', 'head': 6, 'deprel': 'amod', 'deps': '6:amod',
           'misc': 'Id=001n|LTranslit=važlyvyj|Translit=važlyvych'},
          {'id': (6,), 'text': 'сцен', 'lemma': 'сцена', 'upos': 'NOUN', 'xpos': 'Ncfpgn',
           'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Plur', 'head': 2, 'deprel': 'nmod', 'deps': '2:nmod',
           'misc': 'Id=001o|LTranslit=scena|Translit=scen'},
          {'id': (7,), 'text': 'у', 'lemma': 'у', 'upos': 'ADP', 'xpos': 'Spsl', 'feats': 'Case=Loc', 'head': 8,
           'deprel': 'case', 'deps': '8:case', 'misc': 'Id=001p|LTranslit=u|Translit=u'},
          {'id': (8,), 'text': 'драмі', 'lemma': 'драма', 'upos': 'NOUN', 'xpos': 'Ncfsln',
           'feats': 'Animacy=Inan|Case=Loc|Gender=Fem|Number=Sing', 'head': 6, 'deprel': 'nmod', 'deps': '6:nmod',
           'misc': 'Id=001q|LTranslit=drama|Translit=drami'},
          {'id': (9,), 'text': 'Лесі', 'lemma': 'Леся', 'upos': 'PROPN', 'xpos': 'Npfsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Fem|NameType=Giv|Number=Sing', 'head': 8, 'deprel': 'nmod',
           'deps': '8:nmod', 'misc': 'Id=001r|LTranslit=Leśа|Translit=Lesi'},
          {'id': (10,), 'text': 'Українки', 'lemma': 'Українка', 'upos': 'PROPN', 'xpos': 'Npfsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Fem|NameType=Sur|Number=Sing', 'head': 9, 'deprel': 'flat:name',
           'deps': '9:flat:name', 'misc': 'Id=001s|LTranslit=Ukrajinka|Translit=Ukrajinky'},
          {'id': (11,), 'text': '«', 'lemma': '«', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Quot', 'head': 12,
           'deprel': 'punct', 'deps': '12:punct', 'misc': 'Id=001t|LTranslit=«|SpaceAfter=No|Translit=«'},
          {'id': (12,), 'text': 'Руфін', 'lemma': 'Руфін', 'upos': 'PROPN', 'xpos': 'Npmsny',
           'feats': 'Animacy=Anim|Case=Nom|Gender=Masc|NameType=Giv|Number=Sing', 'head': 8, 'deprel': 'flat:title',
           'deps': '8:flat:title', 'misc': 'Id=001u|LTranslit=Rufin|Translit=Rufin'},
          {'id': (13,), 'text': 'і', 'lemma': 'і', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 14, 'deprel': 'cc',
           'deps': '14:cc', 'misc': 'Id=001v|LTranslit=i|Translit=i'},
          {'id': (14,), 'text': 'Прісцілла', 'lemma': 'Прісцілла', 'upos': 'PROPN', 'xpos': 'Npfsny',
           'feats': 'Animacy=Anim|Case=Nom|Gender=Fem|NameType=Giv|Number=Sing', 'head': 12, 'deprel': 'conj',
           'deps': '8:flat:title|12:conj', 'misc': 'Id=001w|LTranslit=Priscilla|SpaceAfter=No|Translit=Priscilla'},
          {'id': (15,), 'text': '»', 'lemma': '»', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Quot', 'head': 12,
           'deprel': 'punct', 'deps': '12:punct', 'misc': 'Id=001x|LTranslit=»|SpaceAfter=No|Translit=»'},
          {'id': (16,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 2, 'deprel': 'punct',
           'deps': '2:punct', 'misc': 'Id=001y|LTranslit=.|Translit=.'}],
         []],
     ["TP",
      [{'id': (1,), 'text': 'Ото', 'lemma': 'ото', 'upos': 'PART', 'xpos': 'Q', 'head': 2, 'deprel': 'discourse',
        'deps': '2:discourse', 'misc': 'Id=0gi9|LTranslit=oto|Translit=Oto'},
       {'id': (2,), 'text': 'побув', 'lemma': 'побути', 'upos': 'VERB', 'xpos': 'Vmeis-sm',
        'feats': 'Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=0gia|LTranslit=pobuty|Translit=pobuv'}, {'id': (3, 4), 'text': 'півроку'},
       {'id': (3,), 'text': 'пів', 'lemma': 'пів', 'upos': 'NUM', 'xpos': 'Mlc-a',
        'feats': 'Case=Acc|NumType=Card|Orth=Alt|Uninflect=Yes', 'head': 4, 'deprel': 'nummod:gov',
        'deps': '4:nummod:gov', 'misc': 'Id=38wd|LTranslit=piv|Translit=piv'},
       {'id': (4,), 'text': 'року', 'lemma': 'рік', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 2, 'deprel': 'obl', 'deps': '2:obl',
        'misc': 'Id=38we|LTranslit=rik|Translit=roku'},
       {'id': (5,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 6, 'deprel': 'cc',
        'deps': '6:cc', 'misc': 'Id=0gic|LTranslit=ta|Translit=ta'},
       {'id': (6,), 'text': 'задумав', 'lemma': 'задумати', 'upos': 'VERB', 'xpos': 'Vmeis-sm',
        'feats': 'Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 2, 'deprel': 'conj',
        'deps': '0:root|2:conj', 'misc': 'Id=0gid|LTranslit=zadumaty|Translit=zadumav'},
       {'id': (7,), 'text': 'жениться', 'lemma': 'женитися', 'upos': 'VERB', 'xpos': 'Vmpn',
        'feats': 'Aspect=Imp|VerbForm=Inf', 'head': 6, 'deprel': 'xcomp', 'deps': '6:xcomp',
        'misc': 'Id=0gie|LTranslit=ženytyśа|SpaceAfter=No|Translit=ženyťśа'},
       {'id': (8,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 2, 'deprel': 'punct',
        'deps': '2:punct', 'misc': 'Id=0gif|LTranslit=.|Translit=.'}],
      []],
     ["TP",
      [{'id': (1,), 'text': 'Конструктори', 'lemma': 'конструктор', 'upos': 'NOUN', 'xpos': 'Ncmpny', 'feats':
       'Animacy=Anim|Case=Nom|Gender=Masc|Number=Plur', 'head': 8, 'deprel': 'nsubj', 'deps': '8:nsubj', 'misc':
       'Id=0osf|LTranslit=konstruktor|SpaceAfter=No|Translit=Konstruktory'},
       {'id': (2,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 3, 'deprel': 'punct',
        'deps': '3:punct', 'misc': 'Id=0osg|LTranslit=,|Translit=,'},
       {'id': (3,), 'text': 'удосконалюючи', 'lemma': 'удосконалювати', 'upos': 'VERB', 'xpos': 'Vmpgp', 'feats':
        'Aspect=Imp|Tense=Pres|VerbForm=Conv', 'head': 8, 'deprel': 'advcl', 'deps': '8:advcl', 'misc':
        'Id=0osh|LTranslit=udoskonaľuvaty|Translit=udoskonaľujučy'},
       {'id': (4,), 'text': 'існуючі', 'lemma': 'існуючий', 'upos': 'ADJ', 'xpos': 'Ap--pasnpap', 'feats':
       'Animacy=Inan|Aspect=Imp|Case=Acc|Number=Plur|Tense=Pres|VerbForm=Part|Voice=Act', 'head': 5, 'deprel':
       'amod', 'deps': '5:amod', 'misc': 'Id=0osi|LTranslit=isnujučyj|Translit=isnujuči'},
       {'id': (5,), 'text': 'знаряддя', 'lemma': 'знаряддя', 'upos': 'NOUN', 'xpos': 'Ncnpan', 'feats':
        'Animacy=Inan|Case=Acc|Gender=Neut|Number=Plur', 'head': 3, 'deprel': 'obj', 'deps': '3:obj', 'misc':
        'Id=0osj|LTranslit=znaŕаdďа|Translit=znaŕаdďа'},
       {'id': (6,), 'text': 'праці', 'lemma': 'праця', 'upos': 'NOUN', 'xpos': 'Ncfsgn', 'feats':
        'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 5, 'deprel': 'nmod', 'deps': '5:nmod', 'misc':
        'Id=0osk|LTranslit=praćа|SpaceAfter=No|Translit=praci'},
       {'id': (7,), 'text': ',', 'lemma': ',', 'upos':
       'PUNCT', 'xpos': 'U', 'head': 3, 'deprel': 'punct', 'deps': '3:punct', 'misc': 'Id=0osl|LTranslit=,|Translit=,'},
       {'id': (8,), 'text': 'проектують', 'lemma': 'проектувати', 'upos': 'VERB', 'xpos': 'Vmpip3p', 'feats':
        'Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'head': 0, 'deprel': 'root', 'deps':
        '0:root', 'misc': 'Id=0osm|LTranslit=proektuvaty|Translit=proektujuť'},
       {'id': (9,), 'text': 'різноманітні', 'lemma': 'різноманітний', 'upos': 'ADJ', 'xpos': 'Afp-pasn', 'feats':
        'Animacy=Inan|Case=Acc|Degree=Pos|Number=Plur', 'head': 11, 'deprel': 'amod', 'deps': '11:amod', 'misc':
        'Id=0osn|LTranslit=riznomanitnyj|Translit=riznomanitni'},
       {'id': (10,), 'text': 'металообробні', 'lemma': 'металообробний', 'upos': 'ADJ', 'xpos': 'Ao--pasn', 'feats':
        'Animacy=Inan|Case=Acc|Number=Plur', 'head': 11, 'deprel': 'amod', 'deps': '11:amod', 'misc':
        'Id=0oso|LTranslit=metaloobrobnyj|Translit=metaloobrobni'},
       {'id': (11,), 'text': 'верстати', 'lemma': 'верстат', 'upos': 'NOUN', 'xpos': 'Ncmpan', 'feats':
        'Animacy=Inan|Case=Acc|Gender=Masc|Number=Plur', 'head': 8, 'deprel': 'obj', 'deps': '8:obj|18:nsubj:rel',
        'misc': 'Id=0osp|LTranslit=verstat|Translit=verstaty'},
       {'id': (12,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 15, 'deprel': 'cc', 'deps':
        '15:cc', 'misc': 'Id=0osq|LTranslit=ta|Translit=ta'},
       {'id': (13,), 'text': 'електрифіковані', 'lemma': 'електрифікований', 'upos': 'ADJ', 'xpos': 'Ap--pasnep',
        'feats': 'Animacy=Inan|Aspect=Perf|Case=Acc|Number=Plur|VerbForm=Part|Voice=Pass', 'head': 15, 'deprel':
         'amod', 'deps': '15:amod', 'misc': 'Id=0osr|LTranslit=elektryfikovanyj|Translit=elektryfikovani'},
       {'id': (14,), 'text': 'ручні', 'lemma': 'ручний', 'upos': 'ADJ', 'xpos': 'Ao--pasn', 'feats':
        'Animacy=Inan|Case=Acc|Number=Plur', 'head': 15, 'deprel': 'amod', 'deps': '15:amod', 'misc':
        'Id=0oss|LTranslit=ručnyj|Translit=ručni'},
       {'id': (15,), 'text': 'інструменти', 'lemma': 'інструмент', 'upos': 'NOUN', 'xpos': 'Ncmpan', 'feats':
        'Animacy=Inan|Case=Acc|Gender=Masc|Number=Plur', 'head': 11, 'deprel': 'conj', 'deps': '8:obj|11:conj',
        'misc': 'Id=0ost|LTranslit=instrument|SpaceAfter=No|Translit=instrumenty'},
       {'id': (16,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 18, 'deprel': 'punct', 'deps':
        '18:punct', 'misc': 'Id=0osu|LTranslit=,|Translit=,'},
       {'id': (17,), 'text': 'які', 'lemma': 'який', 'upos': 'DET', 'xpos': 'Pr----pna', 'feats':
        'Case=Nom|Number=Plur|PronType=Rel', 'head': 18, 'deprel': 'nsubj', 'deps': '11:ref|18:nsubj',
        'misc': 'Id=0osv|LTranslit=jakyj|Translit=jaki'},
       {'id': (18,), 'text': 'відрізняються', 'lemma': 'відрізнятися', 'upos': 'VERB', 'xpos': 'Vmpip3p', 'feats':
        'Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'head': 11, 'deprel': 'acl:relcl', 'deps':
        '11:acl:relcl', 'misc': 'Id=0osw|LTranslit=vidrizńаtyśа|Translit=vidrizńаjuťśа'},
       {'id': (19,), 'text': 'різними', 'lemma': 'різний', 'upos': 'ADJ', 'xpos': 'Ao--pif', 'feats':
        'Case=Ins|Number=Plur', 'head': 20, 'deprel': 'amod', 'deps': '20:amod', 'misc':
        'Id=0osx|LTranslit=riznyj|Translit=riznymy'},
       {'id': (20,), 'text': 'параметрами', 'lemma': 'параметр', 'upos': 'NOUN', 'xpos': 'Ncmpin', 'feats':
        'Animacy=Inan|Case=Ins|Gender=Masc|Number=Plur', 'head': 18, 'deprel': 'obl', 'deps': '18:obl', 'misc':
        'Id=0osy|LTranslit=parametr|Translit=parametramy'},
       {'id': (21,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 22, 'deprel': 'cc', 'deps':
        '22:cc', 'misc': 'Id=0osz|LTranslit=ta|Translit=ta'},
       {'id': (22,), 'text': 'якістю', 'lemma': 'якість', 'upos': 'NOUN', 'xpos': 'Ncfsin', 'feats':
        'Animacy=Inan|Case=Ins|Gender=Fem|Number=Sing', 'head': 20, 'deprel': 'conj', 'deps': '18:obl|20:conj',
        'misc': 'Id=0ot0|LTranslit=jakisť|Translit=jakisťu'},
       {'id': (23,), 'text': 'обробки', 'lemma': 'обробка', 'upos': 'NOUN', 'xpos': 'Ncfsgn', 'feats':
        'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 22, 'deprel': 'nmod', 'deps': '22:nmod', 'misc':
        'Id=0ot1|LTranslit=obrobka|SpaceAfter=No|Translit=obrobky'},
       {'id': (24,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 8, 'deprel': 'punct', 'deps':
        '8:punct', 'misc': 'Id=0ot2|LTranslit=.|Translit=.'}],
      ["Конструктори, удосконалюючи існуючі праці знаряддя, проектують різноманітні верстати металообробні та "
       "електрифіковані інструменти ручні, які відрізняються параметрами різними та обробки якістю.",
       "Конструктори, удосконалюючи знаряддя існуючі праці, проектують різноманітні верстати металообробні та"
       " електрифіковані інструменти ручні, які відрізняються параметрами різними та обробки якістю."]],
    ["TP",
     [{'id': (1,), 'text': 'Бюро', 'lemma': 'бюро', 'upos': 'NOUN', 'xpos': 'Ncnsnn',
       'feats': 'Animacy=Inan|Case=Nom|Gender=Neut|Number=Sing|Uninflect=Yes', 'head': 4, 'deprel': 'nsubj',
       'deps': '4:nsubj|5:nsubj:x', 'misc': 'Id=17yi|LTranslit=buro|Translit=Buro'},
      {'id': (2,), 'text': 'Інформації', 'lemma': 'інформація', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
       'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 1, 'deprel': 'nmod', 'deps': '1:nmod',
       'misc': 'Id=17yj|LTranslit=informacija|Translit=Informaciji'},
      {'id': (3,), 'text': 'УГВР', 'lemma': 'УГВР', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 1, 'deprel': 'nmod',
       'deps': '1:nmod', 'misc': 'Id=17yk|LTranslit=UHVR|Translit=UHVR'},
      {'id': (4,), 'text': 'уповноважене', 'lemma': 'уповноважений', 'upos': 'ADJ', 'xpos': 'Ap-nsns-ep',
       'feats': 'Aspect=Perf|Case=Nom|Gender=Neut|Number=Sing|VerbForm=Part|Voice=Pass', 'head': 0, 'deprel': 'root',
       'deps': '0:root', 'misc': 'Id=17yl|LTranslit=upovnovaženyj|Translit=upovnovažene'},
      {'id': (5,), 'text': 'поінформувати', 'lemma': 'поінформувати', 'upos': 'VERB', 'xpos': 'Vmen',
       'feats': 'Aspect=Perf|VerbForm=Inf', 'head': 4, 'deprel': 'xcomp', 'deps': '4:xcomp',
       'misc': 'Id=17ym|LTranslit=poinformuvaty|Translit=poinformuvaty'},
      {'id': (6,), 'text': 'кадри', 'lemma': 'кадр', 'upos': 'NOUN', 'xpos': 'Ncmpan',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Plur', 'head': 5, 'deprel': 'obj', 'deps': '5:obj',
       'misc': 'Id=17yn|LTranslit=kadr|Translit=kadry'},
      {'id': (7,), 'text': 'підпілля', 'lemma': 'підпілля', 'upos': 'NOUN', 'xpos': 'Ncnsgn',
       'feats': 'Animacy=Inan|Case=Gen|Gender=Neut|Number=Sing', 'head': 6, 'deprel': 'nmod', 'deps': '6:nmod',
       'misc': 'Id=17yo|LTranslit=pidpilľа|Translit=pidpilľа'},
      {'id': (8,), 'text': 'і', 'lemma': 'і', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 11, 'deprel': 'cc',
       'deps': '11:cc', 'misc': 'Id=17yp|LTranslit=i|Translit=i'},
      {'id': (9,), 'text': 'ввесь', 'lemma': 'ввесь', 'upos': 'DET', 'xpos': 'Pg--mnsaa',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Sing|PronType=Tot', 'head': 11, 'deprel': 'det',
       'deps': '11:det', 'misc': 'Id=17yq|LTranslit=vveś|Translit=vveś'},
      {'id': (10,), 'text': 'український', 'lemma': 'український', 'upos': 'ADJ', 'xpos': 'Ao-msafn',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Sing', 'head': 11, 'deprel': 'amod', 'deps': '11:amod',
       'misc': 'Id=17yr|LTranslit=ukrajinśkyj|Translit=ukrajinśkyj'},
      {'id': (11,), 'text': 'народ', 'lemma': 'народ', 'upos': 'NOUN', 'xpos': 'Ncmsan',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Sing', 'head': 6, 'deprel': 'conj', 'deps': '5:obj|6:conj',
       'misc': 'Id=17ys|LTranslit=narod|Translit=narod'},
      {'id': (12,), 'text': 'про', 'lemma': 'про', 'upos': 'ADP', 'xpos': 'Spsa',
       'feats': 'Case=Acc', 'head': 13, 'deprel': 'case', 'deps': '13:case',
       'misc': 'Id=17yt|LTranslit=pro|Translit=pro'},
      {'id': (13,), 'text': 'те', 'lemma': 'те', 'upos': 'PRON', 'xpos': 'Pd--nnsan',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Neut|Number=Sing|PronType=Dem', 'head': 5, 'deprel': 'obl',
       'deps': '5:obl', 'misc': 'Id=17yu|LTranslit=te|SpaceAfter=No|Translit=te'},
      {'id': (14,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 42, 'deprel': 'punct',
       'deps': '42:punct', 'misc': 'Id=17yv|LTranslit=,|Translit=,'},
      {'id': (15,), 'text': 'що', 'lemma': 'що', 'upos': 'SCONJ', 'xpos': 'Css', 'head': 42, 'deprel': 'mark',
       'deps': '42:mark', 'misc': 'Id=17yw|LTranslit=ščo|Translit=ščo'},
      {'id': (16,), 'text': 'після', 'lemma': 'після', 'upos': 'ADP', 'xpos': 'Spsg',
       'feats': 'Case=Gen', 'head': 17, 'deprel': 'case', 'deps': '17:case',
       'misc': 'Id=17yx|LTranslit=pisľа|Translit=pisľа'},
      {'id': (17,), 'text': 'смерти', 'lemma': 'смерть', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
       'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Orth=Alt', 'head': 42, 'deprel': 'obl', 'deps': '42:obl',
       'misc': 'Id=17yy|LTranslit=smerť|Translit=smerty'},
      {'id': (18,), 'text': 'сл', 'lemma': 'сл.', 'upos': 'ADJ', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Case=Gen|Gender=Masc|Number=Sing|Uninflect=Yes', 'head': 20, 'deprel': 'amod',
       'deps': '20:amod', 'misc': 'Id=17yz|LTranslit=sl.|SpaceAfter=No|Translit=sl'},
      {'id': (19,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 18, 'deprel': 'punct',
       'deps': '18:punct', 'misc': 'Id=17z0|LTranslit=.|Translit=.'},
      {'id': (20,), 'text': 'п', 'lemma': 'п.', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing|Uninflect=Yes', 'head': 17, 'deprel': 'nmod',
       'deps': '17:nmod', 'misc': 'Id=17z1|LTranslit=p.|SpaceAfter=No|Translit=p'},
      {'id': (21,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 20, 'deprel': 'punct',
       'deps': '20:punct', 'misc': 'Id=17z2|LTranslit=.|Translit=.'},
      {'id': (22,), 'text': 'генерал', 'lemma': 'генерал', 'upos': 'NOUN', 'xpos': 'Ncmsny',
       'feats': 'Animacy=Anim|Case=Nom|Gender=Masc|Number=Sing', 'head': 24, 'deprel': 'compound',
       'deps': '24:compound', 'misc': 'Id=17z3|LTranslit=heneral|SpaceAfter=No|Translit=heneral'},
      {'id': (23,), 'text': '-', 'lemma': '-', 'upos': 'PUNCT', 'xpos': 'U',
       'feats': 'PunctType=Hyph', 'head': 22, 'deprel': 'punct', 'deps': '22:punct',
       'misc': 'Id=17z4|LTranslit=-|SpaceAfter=No|Translit=-'},
      {'id': (24,), 'text': 'хорунжого', 'lemma': 'хорунжий', 'upos': 'NOUN', 'xpos': 'Ao-msgf',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing', 'head': 20, 'deprel': 'flat:title',
       'deps': '20:flat:title', 'misc': 'Id=17z5|LTranslit=chorunžyj|Translit=chorunžoho'},
      {'id': (25,), 'text': 'УПА', 'lemma': 'УПА', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 24, 'deprel': 'nmod',
       'deps': '24:nmod', 'misc': 'Id=17z6|LTranslit=UPA|Translit=UPA'},
      {'id': (26,), 'text': 'Романа', 'lemma': 'Роман', 'upos': 'PROPN', 'xpos': 'Npmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Giv|Number=Sing', 'head': 24, 'deprel': 'flat:title',
       'deps': '24:flat:title', 'misc': 'Id=17z7|LTranslit=Roman|Translit=Romana'},
      {'id': (27,), 'text': 'Шухевича', 'lemma': 'Шухевич', 'upos': 'PROPN', 'xpos': 'Npmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Sur|Number=Sing', 'head': 26, 'deprel': 'flat:name',
       'deps': '26:flat:name', 'misc': 'Id=17z8|LTranslit=Šuchevyč|Translit=Šuchevyča'},
      {'id': (28,), 'text': '-', 'lemma': '-', 'upos': 'PUNCT', 'xpos': 'U',
       'feats': 'PunctType=Dash', 'head': 29, 'deprel': 'punct', 'deps': '29:punct',
       'misc': 'Id=17z9|LTranslit=-|Translit=-'},
      {'id': (29,), 'text': 'Лозовського', 'lemma': 'Лозовський', 'upos': 'PROPN', 'xpos': 'Npmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Sur|Number=Sing', 'head': 27, 'deprel': 'appos',
       'deps': '27:appos', 'misc': 'Id=17za|LTranslit=Lozovśkyj|SpaceAfter=No|Translit=Lozovśkoho'},
      {'id': (30,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 31, 'deprel': 'punct',
       'deps': '31:punct', 'misc': 'Id=17zb|LTranslit=,|Translit=,'},
      {'id': (31,), 'text': 'Чупринки', 'lemma': 'Чупринка', 'upos': 'PROPN', 'xpos': 'Npmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Sur|Number=Sing', 'head': 29, 'deprel': 'conj',
       'deps': '27:appos|29:conj', 'misc': 'Id=17zc|LTranslit=Čuprynka|Translit=Čuprynky'},
      {'id': (32,), 'text': '-', 'lemma': '-', 'upos': 'PUNCT', 'xpos': 'U',
       'feats': 'PunctType=Dash', 'head': 29, 'deprel': 'punct', 'deps': '29:punct',
       'misc': 'Id=17zd|LTranslit=-|Translit=-'},
      {'id': (33,), 'text': 'пост', 'lemma': 'пост', 'upos': 'NOUN', 'xpos': 'Ncmsan',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Sing', 'head': 42, 'deprel': 'obj', 'deps': '42:obj',
       'misc': 'Id=17ze|LTranslit=post|Translit=post'},
      {'id': (34,), 'text': 'Голови', 'lemma': 'голова', 'upos': 'NOUN', 'xpos': 'Ncmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing', 'head': 33, 'deprel': 'nmod', 'deps': '33:nmod',
       'misc': 'Id=17zf|LTranslit=holova|Translit=Holovy'},
      {'id': (35,), 'text': 'Генерального', 'lemma': 'генеральний', 'upos': 'ADJ', 'xpos': 'Ao-msgf',
       'feats': 'Case=Gen|Gender=Masc|Number=Sing', 'head': 36, 'deprel': 'amod', 'deps': '36:amod',
       'misc': 'Id=17zg|LTranslit=heneraľnyj|Translit=Heneraľnoho'},
      {'id': (36,), 'text': 'Секретаріяту', 'lemma': 'секретаріят', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
       'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 34, 'deprel': 'nmod', 'deps': '34:nmod',
       'misc': 'Id=17zh|LTranslit=sekretarijat|Translit=Sekretarijatu'},
      {'id': (37,), 'text': 'УГВР', 'lemma': 'УГВР', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 36, 'deprel': 'nmod',
       'deps': '36:nmod', 'misc': 'Id=17zi|LTranslit=UHVR|Translit=UHVR'},
      {'id': (38,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 40, 'deprel': 'cc',
       'deps': '40:cc', 'misc': 'Id=17zj|LTranslit=ta|Translit=ta'},
      {'id': (39,), 'text': 'Головного', 'lemma': 'головний', 'upos': 'ADJ', 'xpos': 'Afpmsgf',
       'feats': 'Case=Gen|Degree=Pos|Gender=Masc|Number=Sing', 'head': 40, 'deprel': 'amod', 'deps': '40:amod',
       'misc': 'Id=17zk|LTranslit=holovnyj|Translit=Holovnoho'},
      {'id': (40,), 'text': 'Командира', 'lemma': 'командир', 'upos': 'NOUN', 'xpos': 'Ncmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing', 'head': 34, 'deprel': 'conj',
       'deps': '33:nmod|34:conj', 'misc': 'Id=17zl|LTranslit=komandyr|Translit=Komandyra'},
      {'id': (41,), 'text': 'УПА', 'lemma': 'УПА', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 40, 'deprel': 'nmod',
       'deps': '40:nmod', 'misc': 'Id=17zm|LTranslit=UPA|Translit=UPA'},
      {'id': (42,), 'text': 'обняв', 'lemma': 'обняти', 'upos': 'VERB', 'xpos': 'Vmeis-sm',
       'feats': 'Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 13, 'deprel': 'acl',
       'deps': '13:acl', 'misc': 'Id=17zn|LTranslit=obńаty|Translit=obńаv'},
      {'id': (43,), 'text': 'полк', 'lemma': 'полк.', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Anim|Case=Nom|Gender=Masc|Number=Sing|Uninflect=Yes', 'head': 42, 'deprel': 'nsubj',
       'deps': '42:nsubj', 'misc': 'Id=17zo|LTranslit=polk.|SpaceAfter=No|Translit=polk'},
      {'id': (44,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 43, 'deprel': 'punct',
       'deps': '43:punct', 'misc': 'Id=17zp|LTranslit=.|Translit=.'},
      {'id': (45,), 'text': 'УПА', 'lemma': 'УПА', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 43, 'deprel': 'nmod',
       'deps': '43:nmod', 'misc': 'Id=17zq|LTranslit=UPA|Translit=UPA'},
      {'id': (46,), 'text': 'Василь', 'lemma': 'Василь', 'upos': 'PROPN', 'xpos': 'Npmsny',
       'feats': 'Animacy=Anim|Case=Nom|Gender=Masc|NameType=Giv|Number=Sing', 'head': 43, 'deprel': 'flat:title',
       'deps': '43:flat:title', 'misc': 'Id=17zr|LTranslit=Vasyľ|Translit=Vasyľ'},
      {'id': (47,), 'text': 'Коваль', 'lemma': 'Коваль', 'upos': 'PROPN', 'xpos': 'Npmsny',
       'feats': 'Animacy=Anim|Case=Nom|Gender=Masc|NameType=Sur|Number=Sing', 'head': 46, 'deprel': 'flat:name',
       'deps': '46:flat:name', 'misc': 'Id=17zs|LTranslit=Kovaľ|SpaceAfter=No|Translit=Kovaľ'},
      {'id': (48,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 4, 'deprel': 'punct',
       'deps': '4:punct', 'misc': 'Id=17zt|LTranslit=.|Translit=.'}],
     ["Інформації Бюро УГВР уповноважене поінформувати підпілля кадри і ввесь народ український про те, що після смерти"
      " сл. п. генерал-УПА хорунжого Романа Шухевича - Лозовського, Чупринки - пост Голови Генерального УГВР "
      "Секретаріяту та Головного УПА Командира обняв полк. УПА Василь Коваль.",
      "Інформації Бюро УГВР уповноважене поінформувати підпілля кадри і ввесь народ український про те, що після смерти"
      " сл. п. генерал-УПА хорунжого Романа Шухевича - Лозовського, Чупринки - пост Голови Генерального УГВР "
      "Секретаріяту та Командира Головного УПА обняв полк. УПА Василь Коваль.",
      "Інформації Бюро УГВР уповноважене поінформувати підпілля кадри і ввесь народ український про те, що після смерти"
      " сл. п. генерал-УПА хорунжого Романа Шухевича - Лозовського, Чупринки - пост Голови Секретаріяту Генерального "
      "УГВР та Головного УПА Командира обняв полк. УПА Василь Коваль.",
      "Інформації Бюро УГВР уповноважене поінформувати підпілля кадри і ввесь народ український про те, що після смерти"
      " сл. п. генерал-УПА хорунжого Романа Шухевича - Лозовського, Чупринки - пост Голови Секретаріяту Генерального"
      " УГВР та Командира Головного УПА обняв полк. УПА Василь Коваль."]],
     ["TP",
      [{'id': (1,), 'text': 'трохи', 'lemma': 'трохи', 'upos': 'ADV', 'xpos': 'R', 'head': 2, 'deprel': 'advmod',
        'deps': '2:advmod', 'misc': 'Id=1rz5|LTranslit=trochy|Translit=trochy'},
       {'id': (2,), 'text': 'підофігів', 'lemma': 'підофігіти', 'upos': 'VERB', 'xpos': 'Vmpis-sm',
        'feats': 'Aspect=Imp|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=1rz6|LTranslit=pidofihity|SpaceAfter=No|Translit=pidofihiv'},
       {'id': (3,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 5, 'deprel': 'punct',
        'deps': '5:punct', 'misc': 'Id=1rz7|LTranslit=,|SpaceAfter=No|Translit=,'},
       {'id': (4,), 'text': 'коли', 'lemma': 'коли', 'upos': 'ADV', 'xpos': 'Pr------r',
        'feats': 'PronType=Rel', 'head': 5, 'deprel': 'advmod', 'deps': '5:advmod',
        'misc': 'Id=1rz8|LTranslit=koly|Translit=koly'},
       {'id': (5,), 'text': 'побачив', 'lemma': 'побачити', 'upos': 'VERB', 'xpos': 'Vmeis-sm',
        'feats': 'Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 2, 'deprel': 'advcl',
        'deps': '2:advcl', 'misc': 'Id=1rz9|LTranslit=pobačyty|SpaceAfter=No|Translit=pobačyv'},
       {'id': (6,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 15, 'deprel': 'punct',
        'deps': '15:punct', 'misc': 'Id=1rza|LTranslit=,|SpaceAfter=No|Translit=,'},
       {'id': (7,), 'text': 'що', 'lemma': 'що', 'upos': 'SCONJ', 'xpos': 'Css', 'head': 15, 'deprel': 'mark',
        'deps': '15:mark', 'misc': 'Id=1rzb|LTranslit=ščo|Translit=ščo'},
       {'id': (8,), 'text': 'в', 'lemma': 'в', 'upos': 'ADP', 'xpos': 'Spsl',
        'feats': 'Case=Loc', 'head': 10, 'deprel': 'case', 'deps': '10:case', 'misc': 'Id=1rzc|LTranslit=v|Translit=v'},
       {'id': (9,), 'text': 'угорськ', 'lemma': 'угорськ.', 'upos': 'ADJ', 'xpos': 'Y',
        'feats': 'Abbr=Yes|Case=Loc|Gender=Masc|Number=Sing|Uninflect=Yes', 'head': 10, 'deprel': 'amod',
        'deps': '10:amod', 'misc': 'Id=1rzd|LTranslit=uhorśk.|Translit=uhorśk'},
       {'id': (10,), 'text': 'паспорті', 'lemma': 'паспорт', 'upos': 'NOUN', 'xpos': 'Ncmsln',
        'feats': 'Animacy=Inan|Case=Loc|Gender=Masc|Number=Sing', 'head': 15, 'deprel': 'obl', 'deps': '15:obl|18:obl',
        'misc': 'Id=1rze|LTranslit=pasport|Translit=pasporti'},
       {'id': (11,), 'text': 'графа', 'lemma': 'графа', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 15, 'deprel': 'nsubj',
        'deps': '15:nsubj|18:nsubj', 'misc': 'Id=1rzf|LTranslit=hrafa|SpaceAfter=No|Translit=hrafa'},
       {'id': (12,), 'text': '"', 'lemma': '"', 'upos': 'PUNCT', 'xpos': 'U',
        'feats': 'PunctType=Quot', 'head': 13, 'deprel': 'punct', 'deps': '13:punct',
        'misc': 'Id=1rzg|LTranslit="|SpaceAfter=No|Translit="'},
       {'id': (13,), 'text': 'національність', 'lemma': 'національність', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 11, 'deprel': 'flat:title',
        'deps': '11:flat:title', 'misc': 'Id=1rzh|LTranslit=nacionaľnisť|SpaceAfter=No|Translit=nacionaľnisť'},
       {'id': (14,), 'text': '"', 'lemma': '"', 'upos': 'PUNCT', 'xpos': 'U',
        'feats': 'PunctType=Quot', 'head': 13, 'deprel': 'punct', 'deps': '13:punct',
        'misc': 'Id=1rzi|LTranslit="|SpaceAfter=No|Translit="'},
       {'id': (15,), 'text': 'виділена', 'lemma': 'виділений', 'upos': 'ADJ', 'xpos': 'Ap-fsns-ep',
        'feats': 'Aspect=Perf|Case=Nom|Gender=Fem|Number=Sing|VerbForm=Part|Voice=Pass', 'head': 5, 'deprel': 'ccomp',
        'deps': '5:ccomp', 'misc': 'Id=1rzj|LTranslit=vydilenyj|Translit=vydilena'},
       {'id': (16,), 'text': 'жирним', 'lemma': 'жирний', 'upos': 'NOUN', 'xpos': 'Ao-msif',
        'feats': 'Animacy=Inan|Case=Ins|Gender=Masc|Number=Sing', 'head': 15, 'deprel': 'obl', 'deps': '15:obl',
        'misc': 'Id=1rzk|LTranslit=žyrnyj|Translit=žyrnym'},
       {'id': (17,), 'text': 'і', 'lemma': 'і', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 18, 'deprel': 'cc',
        'deps': '18:cc', 'misc': 'Id=1rzl|LTranslit=i|Translit=i'},
       {'id': (18,), 'text': 'більша', 'lemma': 'більший', 'upos': 'ADJ', 'xpos': 'Afcfsns',
        'feats': 'Case=Nom|Degree=Cmp|Gender=Fem|Number=Sing', 'head': 15, 'deprel': 'conj', 'deps': '5:ccomp|15:conj',
        'misc': 'Id=1rzm|LTranslit=biľšyj|Translit=biľša'},
       {'id': (19,), 'text': 'за', 'lemma': 'за', 'upos': 'ADP', 'xpos': 'Spsa',
        'feats': 'Case=Acc', 'head': 20, 'deprel': 'case', 'deps': '20:case',
        'misc': 'Id=1rzn|LTranslit=za|Translit=za'},
       {'id': (20,), 'text': 'решту', 'lemma': 'решта', 'upos': 'NOUN', 'xpos': 'Ncfsan',
        'feats': 'Animacy=Inan|Case=Acc|Gender=Fem|Number=Sing', 'head': 18, 'deprel': 'obl', 'deps': '18:obl',
        'misc': 'Id=1rzo|LTranslit=rešta|Translit=reštu'},
       {'id': (21,), 'text': 'тексту', 'lemma': 'текст', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 20, 'deprel': 'nmod', 'deps': '20:nmod',
        'misc': 'Id=1rzp|LTranslit=tekst|Translit=tekstu'},
       {'id': (22,), 'text': 'О_о', 'lemma': 'О_о', 'upos': 'SYM', 'xpos': 'X', 'head': 2, 'deprel': 'discourse',
        'deps': '2:discourse', 'misc': 'Id=1rzq|LTranslit=O_o|Translit=O_o'}],
      ['підофігів трохи,коли побачив,що в паспорті угорськ графа"національність"жирним виділена і більша за'
       ' тексту решту О_о']],
     ["TP",
      [{'id': (1,), 'text': '—', 'lemma': '—', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Dash', 'head': 2,
        'deprel': 'punct', 'deps': '2:punct', 'misc': 'Id=02ub|LTranslit=—|Translit=—'},
       {'id': (2,), 'text': 'Було', 'lemma': 'бути', 'upos': 'VERB', 'xpos': 'Vapis-sn', 'feats':
        'Aspect=Imp|Gender=Neut|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=02uc|LTranslit=buty|Translit=Bulo'},
       {'id': (3,), 'text': 'трохи', 'lemma': 'трохи', 'upos': 'ADV', 'xpos': 'R', 'head': 2, 'deprel': 'advmod',
        'deps': '2:advmod', 'misc': 'Id=02ud|LTranslit=trochy|SpaceAfter=No|Translit=trochy'},
       {'id': (4,), 'text': '…', 'lemma': '…', 'upos': 'PUNCT', 'xpos': 'U', 'head': 2, 'deprel': 'punct',
        'deps': '2:punct', 'misc': 'Id=02ue|LTranslit=…|Translit=…'}],
      ["— Трохи було…"]]
    ])
    def test_ud_augment(self, name, doc, expected):
        doc_to_aug = DataAugmentation(doc)
        doc_to_aug.augment()
        aug_sents = doc_to_aug.get_aug_docs()
        actual = [doc_to_text(aug_s) for aug_s in aug_sents]
        print(actual)
        print(len(actual))
        assert_equal(actual, expected)