from nose.tools import assert_equal
from parameterized import parameterized
import unittest
from scripts.data_augmentation.augment import doc_to_text
from scripts.data_augmentation.ud_augment import DataAugmentation

class TestUDAugment(unittest.TestCase):
    @parameterized.expand([
        ["TP",
         [{'id': (1,), 'text': 'У', 'lemma': 'у', 'upos': 'ADP', 'xpos': 'Spsl', 'feats': 'Case=Loc', 'head': 2,
           'deprel': 'case', 'deps': '2:case', 'misc': 'Id=0003|LTranslit=u|Translit=U'},
          {'id': (2,), 'text': 'домі', 'lemma': 'дім', 'upos': 'NOUN', 'xpos': 'Ncmsln',
           'feats': 'Animacy=Inan|Case=Loc|Gender=Masc|Number=Sing', 'head': 6, 'deprel': 'obl', 'deps': '6:obl',
           'misc': 'Id=0004|LTranslit=dim|Translit=domi'},
          {'id': (3,), 'text': 'римського', 'lemma': 'римський', 'upos': 'ADJ', 'xpos': 'Ao-msgf',
           'feats': 'Case=Gen|Gender=Masc|Number=Sing', 'head': 4, 'deprel': 'amod', 'deps': '4:amod',
           'misc': 'Id=0005|LTranslit=rymśkyj|Translit=rymśkoho'},
          {'id': (4,), 'text': 'патриція', 'lemma': 'патрицій', 'upos': 'NOUN', 'xpos': 'Ncmsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing', 'head': 2, 'deprel': 'nmod', 'deps': '2:nmod',
           'misc': 'Id=0006|LTranslit=patrycij|Translit=patrycija'},
          {'id': (5,), 'text': 'Руфіна', 'lemma': 'Руфін', 'upos': 'PROPN', 'xpos': 'Npmsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Giv|Number=Sing', 'head': 4, 'deprel': 'flat:title',
           'deps': '4:flat:title', 'misc': 'Id=0007|LTranslit=Rufin|Translit=Rufina'},
          {'id': (6,), 'text': 'була', 'lemma': 'бути', 'upos': 'VERB', 'xpos': 'Vapis-sf',
           'feats': 'Aspect=Imp|Gender=Fem|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
           'deps': '0:root', 'misc': 'Id=0008|LTranslit=buty|Translit=bula'},
          {'id': (7,), 'text': 'прегарна', 'lemma': 'прегарний', 'upos': 'ADJ', 'xpos': 'Ao-fsns',
           'feats': 'Case=Nom|Gender=Fem|Number=Sing', 'head': 8, 'deprel': 'amod', 'deps': '8:amod',
           'misc': 'Id=0009|LTranslit=preharnyj|Translit=preharna'},
          {'id': (8,), 'text': 'фреска', 'lemma': 'фреска', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
           'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 6, 'deprel': 'nsubj', 'deps': '6:nsubj',
           'misc': 'Id=000a|LTranslit=freska|SpaceAfter=No|Translit=freska'},
          {'id': (9,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 10, 'deprel': 'punct',
           'deps': '10:punct', 'misc': 'Id=000b|LTranslit=,|Translit=,'},
          {'id': (10,), 'text': 'зображення', 'lemma': 'зображення', 'upos': 'NOUN', 'xpos': 'Ncnsnn',
           'feats': 'Animacy=Inan|Case=Nom|Gender=Neut|Number=Sing', 'head': 8, 'deprel': 'appos', 'deps': '8:appos',
           'misc': 'Id=000c|LTranslit=zobraženńа|Translit=zobraženńа'},
          {'id': (11,), 'text': 'Венери', 'lemma': 'Венера', 'upos': 'PROPN', 'xpos': 'Npfsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Fem|NameType=Giv|Number=Sing', 'head': 10, 'deprel': 'nmod',
           'deps': '10:nmod', 'misc': 'Id=000d|LTranslit=Venera|Translit=Venery'},
          {'id': (12,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 13, 'deprel': 'cc',
           'deps': '13:cc', 'misc': 'Id=000e|LTranslit=ta|Translit=ta'},
          {'id': (13,), 'text': 'Адоніса', 'lemma': 'Адоніс', 'upos': 'PROPN', 'xpos': 'Npmsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Giv|Number=Sing', 'head': 11, 'deprel': 'conj',
           'deps': '10:nmod|11:conj', 'misc': 'Id=000f|LTranslit=Adonis|SpaceAfter=No|Translit=Adonisa'},
          {'id': (14,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 6, 'deprel': 'punct',
           'deps': '6:punct', 'misc': 'Id=000g|LTranslit=.|Translit=.'}],
         ["У домі патриція римського Руфіна була фреска прегарна, зображення Венери та Адоніса."]],
        ["TP",
         [{'id': (1,), 'text': 'Це', 'lemma': 'це', 'upos': 'PRON', 'xpos': 'Pd--nnsnn',
           'feats': 'Animacy=Inan|Case=Nom|Gender=Neut|Number=Sing|PronType=Dem', 'head': 2, 'deprel': 'nsubj',
           'deps': '2:nsubj', 'misc': 'Id=001j|LTranslit=ce|Translit=Ce'},
          {'id': (2,), 'text': 'одна', 'lemma': 'один', 'upos': 'DET', 'xpos': 'Pi--f-sna',
           'feats': 'Case=Nom|Gender=Fem|Number=Sing|PronType=Ind', 'head': 0, 'deprel': 'root', 'deps': '0:root',
           'misc': 'Id=001k|LTranslit=odyn|Promoted=Yes|Translit=odna'},
          {'id': (3,), 'text': 'з', 'lemma': 'з', 'upos': 'ADP', 'xpos': 'Spsg', 'feats': 'Case=Gen', 'head': 6,
           'deprel': 'case', 'deps': '6:case', 'misc': 'Id=001l|LTranslit=z|Translit=z'},
          {'id': (4,), 'text': 'надзвичайно', 'lemma': 'надзвичайно', 'upos': 'ADV', 'xpos': 'R', 'head': 5,
           'deprel': 'advmod', 'deps': '5:advmod', 'misc': 'Id=001m|LTranslit=nadzvyčajno|Translit=nadzvyčajno'},
          {'id': (5,), 'text': 'важливих', 'lemma': 'важливий', 'upos': 'ADJ', 'xpos': 'Afp-pgf',
           'feats': 'Case=Gen|Degree=Pos|Number=Plur', 'head': 6, 'deprel': 'amod', 'deps': '6:amod',
           'misc': 'Id=001n|LTranslit=važlyvyj|Translit=važlyvych'},
          {'id': (6,), 'text': 'сцен', 'lemma': 'сцена', 'upos': 'NOUN', 'xpos': 'Ncfpgn',
           'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Plur', 'head': 2, 'deprel': 'nmod', 'deps': '2:nmod',
           'misc': 'Id=001o|LTranslit=scena|Translit=scen'},
          {'id': (7,), 'text': 'у', 'lemma': 'у', 'upos': 'ADP', 'xpos': 'Spsl', 'feats': 'Case=Loc', 'head': 8,
           'deprel': 'case', 'deps': '8:case', 'misc': 'Id=001p|LTranslit=u|Translit=u'},
          {'id': (8,), 'text': 'драмі', 'lemma': 'драма', 'upos': 'NOUN', 'xpos': 'Ncfsln',
           'feats': 'Animacy=Inan|Case=Loc|Gender=Fem|Number=Sing', 'head': 6, 'deprel': 'nmod', 'deps': '6:nmod',
           'misc': 'Id=001q|LTranslit=drama|Translit=drami'},
          {'id': (9,), 'text': 'Лесі', 'lemma': 'Леся', 'upos': 'PROPN', 'xpos': 'Npfsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Fem|NameType=Giv|Number=Sing', 'head': 8, 'deprel': 'nmod',
           'deps': '8:nmod', 'misc': 'Id=001r|LTranslit=Leśа|Translit=Lesi'},
          {'id': (10,), 'text': 'Українки', 'lemma': 'Українка', 'upos': 'PROPN', 'xpos': 'Npfsgy',
           'feats': 'Animacy=Anim|Case=Gen|Gender=Fem|NameType=Sur|Number=Sing', 'head': 9, 'deprel': 'flat:name',
           'deps': '9:flat:name', 'misc': 'Id=001s|LTranslit=Ukrajinka|Translit=Ukrajinky'},
          {'id': (11,), 'text': '«', 'lemma': '«', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Quot', 'head': 12,
           'deprel': 'punct', 'deps': '12:punct', 'misc': 'Id=001t|LTranslit=«|SpaceAfter=No|Translit=«'},
          {'id': (12,), 'text': 'Руфін', 'lemma': 'Руфін', 'upos': 'PROPN', 'xpos': 'Npmsny',
           'feats': 'Animacy=Anim|Case=Nom|Gender=Masc|NameType=Giv|Number=Sing', 'head': 8, 'deprel': 'flat:title',
           'deps': '8:flat:title', 'misc': 'Id=001u|LTranslit=Rufin|Translit=Rufin'},
          {'id': (13,), 'text': 'і', 'lemma': 'і', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 14, 'deprel': 'cc',
           'deps': '14:cc', 'misc': 'Id=001v|LTranslit=i|Translit=i'},
          {'id': (14,), 'text': 'Прісцілла', 'lemma': 'Прісцілла', 'upos': 'PROPN', 'xpos': 'Npfsny',
           'feats': 'Animacy=Anim|Case=Nom|Gender=Fem|NameType=Giv|Number=Sing', 'head': 12, 'deprel': 'conj',
           'deps': '8:flat:title|12:conj', 'misc': 'Id=001w|LTranslit=Priscilla|SpaceAfter=No|Translit=Priscilla'},
          {'id': (15,), 'text': '»', 'lemma': '»', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Quot', 'head': 12,
           'deprel': 'punct', 'deps': '12:punct', 'misc': 'Id=001x|LTranslit=»|SpaceAfter=No|Translit=»'},
          {'id': (16,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 2, 'deprel': 'punct',
           'deps': '2:punct', 'misc': 'Id=001y|LTranslit=.|Translit=.'}],
         []],
     ["TP",
      [{'id': (1,), 'text': 'Ото', 'lemma': 'ото', 'upos': 'PART', 'xpos': 'Q', 'head': 2, 'deprel': 'discourse',
        'deps': '2:discourse', 'misc': 'Id=0gi9|LTranslit=oto|Translit=Oto'},
       {'id': (2,), 'text': 'побув', 'lemma': 'побути', 'upos': 'VERB', 'xpos': 'Vmeis-sm',
        'feats': 'Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=0gia|LTranslit=pobuty|Translit=pobuv'}, {'id': (3, 4), 'text': 'півроку'},
       {'id': (3,), 'text': 'пів', 'lemma': 'пів', 'upos': 'NUM', 'xpos': 'Mlc-a',
        'feats': 'Case=Acc|NumType=Card|Orth=Alt|Uninflect=Yes', 'head': 4, 'deprel': 'nummod:gov',
        'deps': '4:nummod:gov', 'misc': 'Id=38wd|LTranslit=piv|Translit=piv'},
       {'id': (4,), 'text': 'року', 'lemma': 'рік', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 2, 'deprel': 'obl', 'deps': '2:obl',
        'misc': 'Id=38we|LTranslit=rik|Translit=roku'},
       {'id': (5,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 6, 'deprel': 'cc',
        'deps': '6:cc', 'misc': 'Id=0gic|LTranslit=ta|Translit=ta'},
       {'id': (6,), 'text': 'задумав', 'lemma': 'задумати', 'upos': 'VERB', 'xpos': 'Vmeis-sm',
        'feats': 'Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 2, 'deprel': 'conj',
        'deps': '0:root|2:conj', 'misc': 'Id=0gid|LTranslit=zadumaty|Translit=zadumav'},
       {'id': (7,), 'text': 'жениться', 'lemma': 'женитися', 'upos': 'VERB', 'xpos': 'Vmpn',
        'feats': 'Aspect=Imp|VerbForm=Inf', 'head': 6, 'deprel': 'xcomp', 'deps': '6:xcomp',
        'misc': 'Id=0gie|LTranslit=ženytyśа|SpaceAfter=No|Translit=ženyťśа'},
       {'id': (8,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 2, 'deprel': 'punct',
        'deps': '2:punct', 'misc': 'Id=0gif|LTranslit=.|Translit=.'}],
      []],
     ["TP",
      [{'id': (1,), 'text': 'Конструктори', 'lemma': 'конструктор', 'upos': 'NOUN', 'xpos': 'Ncmpny', 'feats':
       'Animacy=Anim|Case=Nom|Gender=Masc|Number=Plur', 'head': 8, 'deprel': 'nsubj', 'deps': '8:nsubj', 'misc':
       'Id=0osf|LTranslit=konstruktor|SpaceAfter=No|Translit=Konstruktory'},
       {'id': (2,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 3, 'deprel': 'punct',
        'deps': '3:punct', 'misc': 'Id=0osg|LTranslit=,|Translit=,'},
       {'id': (3,), 'text': 'удосконалюючи', 'lemma': 'удосконалювати', 'upos': 'VERB', 'xpos': 'Vmpgp', 'feats':
        'Aspect=Imp|Tense=Pres|VerbForm=Conv', 'head': 8, 'deprel': 'advcl', 'deps': '8:advcl', 'misc':
        'Id=0osh|LTranslit=udoskonaľuvaty|Translit=udoskonaľujučy'},
       {'id': (4,), 'text': 'існуючі', 'lemma': 'існуючий', 'upos': 'ADJ', 'xpos': 'Ap--pasnpap', 'feats':
       'Animacy=Inan|Aspect=Imp|Case=Acc|Number=Plur|Tense=Pres|VerbForm=Part|Voice=Act', 'head': 5, 'deprel':
       'amod', 'deps': '5:amod', 'misc': 'Id=0osi|LTranslit=isnujučyj|Translit=isnujuči'},
       {'id': (5,), 'text': 'знаряддя', 'lemma': 'знаряддя', 'upos': 'NOUN', 'xpos': 'Ncnpan', 'feats':
        'Animacy=Inan|Case=Acc|Gender=Neut|Number=Plur', 'head': 3, 'deprel': 'obj', 'deps': '3:obj', 'misc':
        'Id=0osj|LTranslit=znaŕаdďа|Translit=znaŕаdďа'},
       {'id': (6,), 'text': 'праці', 'lemma': 'праця', 'upos': 'NOUN', 'xpos': 'Ncfsgn', 'feats':
        'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 5, 'deprel': 'nmod', 'deps': '5:nmod', 'misc':
        'Id=0osk|LTranslit=praćа|SpaceAfter=No|Translit=praci'},
       {'id': (7,), 'text': ',', 'lemma': ',', 'upos':
       'PUNCT', 'xpos': 'U', 'head': 3, 'deprel': 'punct', 'deps': '3:punct', 'misc': 'Id=0osl|LTranslit=,|Translit=,'},
       {'id': (8,), 'text': 'проектують', 'lemma': 'проектувати', 'upos': 'VERB', 'xpos': 'Vmpip3p', 'feats':
        'Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'head': 0, 'deprel': 'root', 'deps':
        '0:root', 'misc': 'Id=0osm|LTranslit=proektuvaty|Translit=proektujuť'},
       {'id': (9,), 'text': 'різноманітні', 'lemma': 'різноманітний', 'upos': 'ADJ', 'xpos': 'Afp-pasn', 'feats':
        'Animacy=Inan|Case=Acc|Degree=Pos|Number=Plur', 'head': 11, 'deprel': 'amod', 'deps': '11:amod', 'misc':
        'Id=0osn|LTranslit=riznomanitnyj|Translit=riznomanitni'},
       {'id': (10,), 'text': 'металообробні', 'lemma': 'металообробний', 'upos': 'ADJ', 'xpos': 'Ao--pasn', 'feats':
        'Animacy=Inan|Case=Acc|Number=Plur', 'head': 11, 'deprel': 'amod', 'deps': '11:amod', 'misc':
        'Id=0oso|LTranslit=metaloobrobnyj|Translit=metaloobrobni'},
       {'id': (11,), 'text': 'верстати', 'lemma': 'верстат', 'upos': 'NOUN', 'xpos': 'Ncmpan', 'feats':
        'Animacy=Inan|Case=Acc|Gender=Masc|Number=Plur', 'head': 8, 'deprel': 'obj', 'deps': '8:obj|18:nsubj:rel',
        'misc': 'Id=0osp|LTranslit=verstat|Translit=verstaty'},
       {'id': (12,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 15, 'deprel': 'cc', 'deps':
        '15:cc', 'misc': 'Id=0osq|LTranslit=ta|Translit=ta'},
       {'id': (13,), 'text': 'електрифіковані', 'lemma': 'електрифікований', 'upos': 'ADJ', 'xpos': 'Ap--pasnep',
        'feats': 'Animacy=Inan|Aspect=Perf|Case=Acc|Number=Plur|VerbForm=Part|Voice=Pass', 'head': 15, 'deprel':
         'amod', 'deps': '15:amod', 'misc': 'Id=0osr|LTranslit=elektryfikovanyj|Translit=elektryfikovani'},
       {'id': (14,), 'text': 'ручні', 'lemma': 'ручний', 'upos': 'ADJ', 'xpos': 'Ao--pasn', 'feats':
        'Animacy=Inan|Case=Acc|Number=Plur', 'head': 15, 'deprel': 'amod', 'deps': '15:amod', 'misc':
        'Id=0oss|LTranslit=ručnyj|Translit=ručni'},
       {'id': (15,), 'text': 'інструменти', 'lemma': 'інструмент', 'upos': 'NOUN', 'xpos': 'Ncmpan', 'feats':
        'Animacy=Inan|Case=Acc|Gender=Masc|Number=Plur', 'head': 11, 'deprel': 'conj', 'deps': '8:obj|11:conj',
        'misc': 'Id=0ost|LTranslit=instrument|SpaceAfter=No|Translit=instrumenty'},
       {'id': (16,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 18, 'deprel': 'punct', 'deps':
        '18:punct', 'misc': 'Id=0osu|LTranslit=,|Translit=,'},
       {'id': (17,), 'text': 'які', 'lemma': 'який', 'upos': 'DET', 'xpos': 'Pr----pna', 'feats':
        'Case=Nom|Number=Plur|PronType=Rel', 'head': 18, 'deprel': 'nsubj', 'deps': '11:ref|18:nsubj',
        'misc': 'Id=0osv|LTranslit=jakyj|Translit=jaki'},
       {'id': (18,), 'text': 'відрізняються', 'lemma': 'відрізнятися', 'upos': 'VERB', 'xpos': 'Vmpip3p', 'feats':
        'Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'head': 11, 'deprel': 'acl:relcl', 'deps':
        '11:acl:relcl', 'misc': 'Id=0osw|LTranslit=vidrizńаtyśа|Translit=vidrizńаjuťśа'},
       {'id': (19,), 'text': 'різними', 'lemma': 'різний', 'upos': 'ADJ', 'xpos': 'Ao--pif', 'feats':
        'Case=Ins|Number=Plur', 'head': 20, 'deprel': 'amod', 'deps': '20:amod', 'misc':
        'Id=0osx|LTranslit=riznyj|Translit=riznymy'},
       {'id': (20,), 'text': 'параметрами', 'lemma': 'параметр', 'upos': 'NOUN', 'xpos': 'Ncmpin', 'feats':
        'Animacy=Inan|Case=Ins|Gender=Masc|Number=Plur', 'head': 18, 'deprel': 'obl', 'deps': '18:obl', 'misc':
        'Id=0osy|LTranslit=parametr|Translit=parametramy'},
       {'id': (21,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 22, 'deprel': 'cc', 'deps':
        '22:cc', 'misc': 'Id=0osz|LTranslit=ta|Translit=ta'},
       {'id': (22,), 'text': 'якістю', 'lemma': 'якість', 'upos': 'NOUN', 'xpos': 'Ncfsin', 'feats':
        'Animacy=Inan|Case=Ins|Gender=Fem|Number=Sing', 'head': 20, 'deprel': 'conj', 'deps': '18:obl|20:conj',
        'misc': 'Id=0ot0|LTranslit=jakisť|Translit=jakisťu'},
       {'id': (23,), 'text': 'обробки', 'lemma': 'обробка', 'upos': 'NOUN', 'xpos': 'Ncfsgn', 'feats':
        'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 22, 'deprel': 'nmod', 'deps': '22:nmod', 'misc':
        'Id=0ot1|LTranslit=obrobka|SpaceAfter=No|Translit=obrobky'},
       {'id': (24,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 8, 'deprel': 'punct', 'deps':
        '8:punct', 'misc': 'Id=0ot2|LTranslit=.|Translit=.'}],
      ["Конструктори, удосконалюючи існуючі праці знаряддя, проектують різноманітні верстати металообробні та "
       "електрифіковані інструменти ручні, які відрізняються параметрами різними та обробки якістю.",
       "Конструктори, удосконалюючи знаряддя існуючі праці, проектують різноманітні верстати металообробні та"
       " електрифіковані інструменти ручні, які відрізняються параметрами різними та обробки якістю."]],
    ["TP",
     [{'id': (1,), 'text': 'Бюро', 'lemma': 'бюро', 'upos': 'NOUN', 'xpos': 'Ncnsnn',
       'feats': 'Animacy=Inan|Case=Nom|Gender=Neut|Number=Sing|Uninflect=Yes', 'head': 4, 'deprel': 'nsubj',
       'deps': '4:nsubj|5:nsubj:x', 'misc': 'Id=17yi|LTranslit=buro|Translit=Buro'},
      {'id': (2,), 'text': 'Інформації', 'lemma': 'інформація', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
       'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 1, 'deprel': 'nmod', 'deps': '1:nmod',
       'misc': 'Id=17yj|LTranslit=informacija|Translit=Informaciji'},
      {'id': (3,), 'text': 'УГВР', 'lemma': 'УГВР', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 1, 'deprel': 'nmod',
       'deps': '1:nmod', 'misc': 'Id=17yk|LTranslit=UHVR|Translit=UHVR'},
      {'id': (4,), 'text': 'уповноважене', 'lemma': 'уповноважений', 'upos': 'ADJ', 'xpos': 'Ap-nsns-ep',
       'feats': 'Aspect=Perf|Case=Nom|Gender=Neut|Number=Sing|VerbForm=Part|Voice=Pass', 'head': 0, 'deprel': 'root',
       'deps': '0:root', 'misc': 'Id=17yl|LTranslit=upovnovaženyj|Translit=upovnovažene'},
      {'id': (5,), 'text': 'поінформувати', 'lemma': 'поінформувати', 'upos': 'VERB', 'xpos': 'Vmen',
       'feats': 'Aspect=Perf|VerbForm=Inf', 'head': 4, 'deprel': 'xcomp', 'deps': '4:xcomp',
       'misc': 'Id=17ym|LTranslit=poinformuvaty|Translit=poinformuvaty'},
      {'id': (6,), 'text': 'кадри', 'lemma': 'кадр', 'upos': 'NOUN', 'xpos': 'Ncmpan',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Plur', 'head': 5, 'deprel': 'obj', 'deps': '5:obj',
       'misc': 'Id=17yn|LTranslit=kadr|Translit=kadry'},
      {'id': (7,), 'text': 'підпілля', 'lemma': 'підпілля', 'upos': 'NOUN', 'xpos': 'Ncnsgn',
       'feats': 'Animacy=Inan|Case=Gen|Gender=Neut|Number=Sing', 'head': 6, 'deprel': 'nmod', 'deps': '6:nmod',
       'misc': 'Id=17yo|LTranslit=pidpilľа|Translit=pidpilľа'},
      {'id': (8,), 'text': 'і', 'lemma': 'і', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 11, 'deprel': 'cc',
       'deps': '11:cc', 'misc': 'Id=17yp|LTranslit=i|Translit=i'},
      {'id': (9,), 'text': 'ввесь', 'lemma': 'ввесь', 'upos': 'DET', 'xpos': 'Pg--mnsaa',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Sing|PronType=Tot', 'head': 11, 'deprel': 'det',
       'deps': '11:det', 'misc': 'Id=17yq|LTranslit=vveś|Translit=vveś'},
      {'id': (10,), 'text': 'український', 'lemma': 'український', 'upos': 'ADJ', 'xpos': 'Ao-msafn',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Sing', 'head': 11, 'deprel': 'amod', 'deps': '11:amod',
       'misc': 'Id=17yr|LTranslit=ukrajinśkyj|Translit=ukrajinśkyj'},
      {'id': (11,), 'text': 'народ', 'lemma': 'народ', 'upos': 'NOUN', 'xpos': 'Ncmsan',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Sing', 'head': 6, 'deprel': 'conj', 'deps': '5:obj|6:conj',
       'misc': 'Id=17ys|LTranslit=narod|Translit=narod'},
      {'id': (12,), 'text': 'про', 'lemma': 'про', 'upos': 'ADP', 'xpos': 'Spsa',
       'feats': 'Case=Acc', 'head': 13, 'deprel': 'case', 'deps': '13:case',
       'misc': 'Id=17yt|LTranslit=pro|Translit=pro'},
      {'id': (13,), 'text': 'те', 'lemma': 'те', 'upos': 'PRON', 'xpos': 'Pd--nnsan',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Neut|Number=Sing|PronType=Dem', 'head': 5, 'deprel': 'obl',
       'deps': '5:obl', 'misc': 'Id=17yu|LTranslit=te|SpaceAfter=No|Translit=te'},
      {'id': (14,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 42, 'deprel': 'punct',
       'deps': '42:punct', 'misc': 'Id=17yv|LTranslit=,|Translit=,'},
      {'id': (15,), 'text': 'що', 'lemma': 'що', 'upos': 'SCONJ', 'xpos': 'Css', 'head': 42, 'deprel': 'mark',
       'deps': '42:mark', 'misc': 'Id=17yw|LTranslit=ščo|Translit=ščo'},
      {'id': (16,), 'text': 'після', 'lemma': 'після', 'upos': 'ADP', 'xpos': 'Spsg',
       'feats': 'Case=Gen', 'head': 17, 'deprel': 'case', 'deps': '17:case',
       'misc': 'Id=17yx|LTranslit=pisľа|Translit=pisľа'},
      {'id': (17,), 'text': 'смерти', 'lemma': 'смерть', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
       'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Orth=Alt', 'head': 42, 'deprel': 'obl', 'deps': '42:obl',
       'misc': 'Id=17yy|LTranslit=smerť|Translit=smerty'},
      {'id': (18,), 'text': 'сл', 'lemma': 'сл.', 'upos': 'ADJ', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Case=Gen|Gender=Masc|Number=Sing|Uninflect=Yes', 'head': 20, 'deprel': 'amod',
       'deps': '20:amod', 'misc': 'Id=17yz|LTranslit=sl.|SpaceAfter=No|Translit=sl'},
      {'id': (19,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 18, 'deprel': 'punct',
       'deps': '18:punct', 'misc': 'Id=17z0|LTranslit=.|Translit=.'},
      {'id': (20,), 'text': 'п', 'lemma': 'п.', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing|Uninflect=Yes', 'head': 17, 'deprel': 'nmod',
       'deps': '17:nmod', 'misc': 'Id=17z1|LTranslit=p.|SpaceAfter=No|Translit=p'},
      {'id': (21,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 20, 'deprel': 'punct',
       'deps': '20:punct', 'misc': 'Id=17z2|LTranslit=.|Translit=.'},
      {'id': (22,), 'text': 'генерал', 'lemma': 'генерал', 'upos': 'NOUN', 'xpos': 'Ncmsny',
       'feats': 'Animacy=Anim|Case=Nom|Gender=Masc|Number=Sing', 'head': 24, 'deprel': 'compound',
       'deps': '24:compound', 'misc': 'Id=17z3|LTranslit=heneral|SpaceAfter=No|Translit=heneral'},
      {'id': (23,), 'text': '-', 'lemma': '-', 'upos': 'PUNCT', 'xpos': 'U',
       'feats': 'PunctType=Hyph', 'head': 22, 'deprel': 'punct', 'deps': '22:punct',
       'misc': 'Id=17z4|LTranslit=-|SpaceAfter=No|Translit=-'},
      {'id': (24,), 'text': 'хорунжого', 'lemma': 'хорунжий', 'upos': 'NOUN', 'xpos': 'Ao-msgf',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing', 'head': 20, 'deprel': 'flat:title',
       'deps': '20:flat:title', 'misc': 'Id=17z5|LTranslit=chorunžyj|Translit=chorunžoho'},
      {'id': (25,), 'text': 'УПА', 'lemma': 'УПА', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 24, 'deprel': 'nmod',
       'deps': '24:nmod', 'misc': 'Id=17z6|LTranslit=UPA|Translit=UPA'},
      {'id': (26,), 'text': 'Романа', 'lemma': 'Роман', 'upos': 'PROPN', 'xpos': 'Npmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Giv|Number=Sing', 'head': 24, 'deprel': 'flat:title',
       'deps': '24:flat:title', 'misc': 'Id=17z7|LTranslit=Roman|Translit=Romana'},
      {'id': (27,), 'text': 'Шухевича', 'lemma': 'Шухевич', 'upos': 'PROPN', 'xpos': 'Npmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Sur|Number=Sing', 'head': 26, 'deprel': 'flat:name',
       'deps': '26:flat:name', 'misc': 'Id=17z8|LTranslit=Šuchevyč|Translit=Šuchevyča'},
      {'id': (28,), 'text': '-', 'lemma': '-', 'upos': 'PUNCT', 'xpos': 'U',
       'feats': 'PunctType=Dash', 'head': 29, 'deprel': 'punct', 'deps': '29:punct',
       'misc': 'Id=17z9|LTranslit=-|Translit=-'},
      {'id': (29,), 'text': 'Лозовського', 'lemma': 'Лозовський', 'upos': 'PROPN', 'xpos': 'Npmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Sur|Number=Sing', 'head': 27, 'deprel': 'appos',
       'deps': '27:appos', 'misc': 'Id=17za|LTranslit=Lozovśkyj|SpaceAfter=No|Translit=Lozovśkoho'},
      {'id': (30,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 31, 'deprel': 'punct',
       'deps': '31:punct', 'misc': 'Id=17zb|LTranslit=,|Translit=,'},
      {'id': (31,), 'text': 'Чупринки', 'lemma': 'Чупринка', 'upos': 'PROPN', 'xpos': 'Npmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|NameType=Sur|Number=Sing', 'head': 29, 'deprel': 'conj',
       'deps': '27:appos|29:conj', 'misc': 'Id=17zc|LTranslit=Čuprynka|Translit=Čuprynky'},
      {'id': (32,), 'text': '-', 'lemma': '-', 'upos': 'PUNCT', 'xpos': 'U',
       'feats': 'PunctType=Dash', 'head': 29, 'deprel': 'punct', 'deps': '29:punct',
       'misc': 'Id=17zd|LTranslit=-|Translit=-'},
      {'id': (33,), 'text': 'пост', 'lemma': 'пост', 'upos': 'NOUN', 'xpos': 'Ncmsan',
       'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Sing', 'head': 42, 'deprel': 'obj', 'deps': '42:obj',
       'misc': 'Id=17ze|LTranslit=post|Translit=post'},
      {'id': (34,), 'text': 'Голови', 'lemma': 'голова', 'upos': 'NOUN', 'xpos': 'Ncmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing', 'head': 33, 'deprel': 'nmod', 'deps': '33:nmod',
       'misc': 'Id=17zf|LTranslit=holova|Translit=Holovy'},
      {'id': (35,), 'text': 'Генерального', 'lemma': 'генеральний', 'upos': 'ADJ', 'xpos': 'Ao-msgf',
       'feats': 'Case=Gen|Gender=Masc|Number=Sing', 'head': 36, 'deprel': 'amod', 'deps': '36:amod',
       'misc': 'Id=17zg|LTranslit=heneraľnyj|Translit=Heneraľnoho'},
      {'id': (36,), 'text': 'Секретаріяту', 'lemma': 'секретаріят', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
       'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 34, 'deprel': 'nmod', 'deps': '34:nmod',
       'misc': 'Id=17zh|LTranslit=sekretarijat|Translit=Sekretarijatu'},
      {'id': (37,), 'text': 'УГВР', 'lemma': 'УГВР', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 36, 'deprel': 'nmod',
       'deps': '36:nmod', 'misc': 'Id=17zi|LTranslit=UHVR|Translit=UHVR'},
      {'id': (38,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 40, 'deprel': 'cc',
       'deps': '40:cc', 'misc': 'Id=17zj|LTranslit=ta|Translit=ta'},
      {'id': (39,), 'text': 'Головного', 'lemma': 'головний', 'upos': 'ADJ', 'xpos': 'Afpmsgf',
       'feats': 'Case=Gen|Degree=Pos|Gender=Masc|Number=Sing', 'head': 40, 'deprel': 'amod', 'deps': '40:amod',
       'misc': 'Id=17zk|LTranslit=holovnyj|Translit=Holovnoho'},
      {'id': (40,), 'text': 'Командира', 'lemma': 'командир', 'upos': 'NOUN', 'xpos': 'Ncmsgy',
       'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing', 'head': 34, 'deprel': 'conj',
       'deps': '33:nmod|34:conj', 'misc': 'Id=17zl|LTranslit=komandyr|Translit=Komandyra'},
      {'id': (41,), 'text': 'УПА', 'lemma': 'УПА', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 40, 'deprel': 'nmod',
       'deps': '40:nmod', 'misc': 'Id=17zm|LTranslit=UPA|Translit=UPA'},
      {'id': (42,), 'text': 'обняв', 'lemma': 'обняти', 'upos': 'VERB', 'xpos': 'Vmeis-sm',
       'feats': 'Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 13, 'deprel': 'acl',
       'deps': '13:acl', 'misc': 'Id=17zn|LTranslit=obńаty|Translit=obńаv'},
      {'id': (43,), 'text': 'полк', 'lemma': 'полк.', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Anim|Case=Nom|Gender=Masc|Number=Sing|Uninflect=Yes', 'head': 42, 'deprel': 'nsubj',
       'deps': '42:nsubj', 'misc': 'Id=17zo|LTranslit=polk.|SpaceAfter=No|Translit=polk'},
      {'id': (44,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 43, 'deprel': 'punct',
       'deps': '43:punct', 'misc': 'Id=17zp|LTranslit=.|Translit=.'},
      {'id': (45,), 'text': 'УПА', 'lemma': 'УПА', 'upos': 'NOUN', 'xpos': 'Y',
       'feats': 'Abbr=Yes|Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 43, 'deprel': 'nmod',
       'deps': '43:nmod', 'misc': 'Id=17zq|LTranslit=UPA|Translit=UPA'},
      {'id': (46,), 'text': 'Василь', 'lemma': 'Василь', 'upos': 'PROPN', 'xpos': 'Npmsny',
       'feats': 'Animacy=Anim|Case=Nom|Gender=Masc|NameType=Giv|Number=Sing', 'head': 43, 'deprel': 'flat:title',
       'deps': '43:flat:title', 'misc': 'Id=17zr|LTranslit=Vasyľ|Translit=Vasyľ'},
      {'id': (47,), 'text': 'Коваль', 'lemma': 'Коваль', 'upos': 'PROPN', 'xpos': 'Npmsny',
       'feats': 'Animacy=Anim|Case=Nom|Gender=Masc|NameType=Sur|Number=Sing', 'head': 46, 'deprel': 'flat:name',
       'deps': '46:flat:name', 'misc': 'Id=17zs|LTranslit=Kovaľ|SpaceAfter=No|Translit=Kovaľ'},
      {'id': (48,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 4, 'deprel': 'punct',
       'deps': '4:punct', 'misc': 'Id=17zt|LTranslit=.|Translit=.'}],
     ["Інформації Бюро УГВР уповноважене поінформувати підпілля кадри і ввесь народ український про те, що після смерти"
      " сл. п. генерал-УПА хорунжого Романа Шухевича - Лозовського, Чупринки - пост Голови Генерального УГВР "
      "Секретаріяту та Головного УПА Командира обняв полк. УПА Василь Коваль.",
      "Інформації Бюро УГВР уповноважене поінформувати підпілля кадри і ввесь народ український про те, що після смерти"
      " сл. п. генерал-УПА хорунжого Романа Шухевича - Лозовського, Чупринки - пост Голови Генерального УГВР "
      "Секретаріяту та Командира Головного УПА обняв полк. УПА Василь Коваль.",
      "Інформації Бюро УГВР уповноважене поінформувати підпілля кадри і ввесь народ український про те, що після смерти"
      " сл. п. генерал-УПА хорунжого Романа Шухевича - Лозовського, Чупринки - пост Голови Секретаріяту Генерального "
      "УГВР та Головного УПА Командира обняв полк. УПА Василь Коваль.",
      "Інформації Бюро УГВР уповноважене поінформувати підпілля кадри і ввесь народ український про те, що після смерти"
      " сл. п. генерал-УПА хорунжого Романа Шухевича - Лозовського, Чупринки - пост Голови Секретаріяту Генерального"
      " УГВР та Командира Головного УПА обняв полк. УПА Василь Коваль."]],
     ["TP",
      [{'id': (1,), 'text': 'трохи', 'lemma': 'трохи', 'upos': 'ADV', 'xpos': 'R', 'head': 2, 'deprel': 'advmod',
        'deps': '2:advmod', 'misc': 'Id=1rz5|LTranslit=trochy|Translit=trochy'},
       {'id': (2,), 'text': 'підофігів', 'lemma': 'підофігіти', 'upos': 'VERB', 'xpos': 'Vmpis-sm',
        'feats': 'Aspect=Imp|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=1rz6|LTranslit=pidofihity|SpaceAfter=No|Translit=pidofihiv'},
       {'id': (3,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 5, 'deprel': 'punct',
        'deps': '5:punct', 'misc': 'Id=1rz7|LTranslit=,|SpaceAfter=No|Translit=,'},
       {'id': (4,), 'text': 'коли', 'lemma': 'коли', 'upos': 'ADV', 'xpos': 'Pr------r',
        'feats': 'PronType=Rel', 'head': 5, 'deprel': 'advmod', 'deps': '5:advmod',
        'misc': 'Id=1rz8|LTranslit=koly|Translit=koly'},
       {'id': (5,), 'text': 'побачив', 'lemma': 'побачити', 'upos': 'VERB', 'xpos': 'Vmeis-sm',
        'feats': 'Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 2, 'deprel': 'advcl',
        'deps': '2:advcl', 'misc': 'Id=1rz9|LTranslit=pobačyty|SpaceAfter=No|Translit=pobačyv'},
       {'id': (6,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 15, 'deprel': 'punct',
        'deps': '15:punct', 'misc': 'Id=1rza|LTranslit=,|SpaceAfter=No|Translit=,'},
       {'id': (7,), 'text': 'що', 'lemma': 'що', 'upos': 'SCONJ', 'xpos': 'Css', 'head': 15, 'deprel': 'mark',
        'deps': '15:mark', 'misc': 'Id=1rzb|LTranslit=ščo|Translit=ščo'},
       {'id': (8,), 'text': 'в', 'lemma': 'в', 'upos': 'ADP', 'xpos': 'Spsl',
        'feats': 'Case=Loc', 'head': 10, 'deprel': 'case', 'deps': '10:case', 'misc': 'Id=1rzc|LTranslit=v|Translit=v'},
       {'id': (9,), 'text': 'угорськ', 'lemma': 'угорськ.', 'upos': 'ADJ', 'xpos': 'Y',
        'feats': 'Abbr=Yes|Case=Loc|Gender=Masc|Number=Sing|Uninflect=Yes', 'head': 10, 'deprel': 'amod',
        'deps': '10:amod', 'misc': 'Id=1rzd|LTranslit=uhorśk.|Translit=uhorśk'},
       {'id': (10,), 'text': 'паспорті', 'lemma': 'паспорт', 'upos': 'NOUN', 'xpos': 'Ncmsln',
        'feats': 'Animacy=Inan|Case=Loc|Gender=Masc|Number=Sing', 'head': 15, 'deprel': 'obl', 'deps': '15:obl|18:obl',
        'misc': 'Id=1rze|LTranslit=pasport|Translit=pasporti'},
       {'id': (11,), 'text': 'графа', 'lemma': 'графа', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 15, 'deprel': 'nsubj',
        'deps': '15:nsubj|18:nsubj', 'misc': 'Id=1rzf|LTranslit=hrafa|SpaceAfter=No|Translit=hrafa'},
       {'id': (12,), 'text': '"', 'lemma': '"', 'upos': 'PUNCT', 'xpos': 'U',
        'feats': 'PunctType=Quot', 'head': 13, 'deprel': 'punct', 'deps': '13:punct',
        'misc': 'Id=1rzg|LTranslit="|SpaceAfter=No|Translit="'},
       {'id': (13,), 'text': 'національність', 'lemma': 'національність', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 11, 'deprel': 'flat:title',
        'deps': '11:flat:title', 'misc': 'Id=1rzh|LTranslit=nacionaľnisť|SpaceAfter=No|Translit=nacionaľnisť'},
       {'id': (14,), 'text': '"', 'lemma': '"', 'upos': 'PUNCT', 'xpos': 'U',
        'feats': 'PunctType=Quot', 'head': 13, 'deprel': 'punct', 'deps': '13:punct',
        'misc': 'Id=1rzi|LTranslit="|SpaceAfter=No|Translit="'},
       {'id': (15,), 'text': 'виділена', 'lemma': 'виділений', 'upos': 'ADJ', 'xpos': 'Ap-fsns-ep',
        'feats': 'Aspect=Perf|Case=Nom|Gender=Fem|Number=Sing|VerbForm=Part|Voice=Pass', 'head': 5, 'deprel': 'ccomp',
        'deps': '5:ccomp', 'misc': 'Id=1rzj|LTranslit=vydilenyj|Translit=vydilena'},
       {'id': (16,), 'text': 'жирним', 'lemma': 'жирний', 'upos': 'NOUN', 'xpos': 'Ao-msif',
        'feats': 'Animacy=Inan|Case=Ins|Gender=Masc|Number=Sing', 'head': 15, 'deprel': 'obl', 'deps': '15:obl',
        'misc': 'Id=1rzk|LTranslit=žyrnyj|Translit=žyrnym'},
       {'id': (17,), 'text': 'і', 'lemma': 'і', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 18, 'deprel': 'cc',
        'deps': '18:cc', 'misc': 'Id=1rzl|LTranslit=i|Translit=i'},
       {'id': (18,), 'text': 'більша', 'lemma': 'більший', 'upos': 'ADJ', 'xpos': 'Afcfsns',
        'feats': 'Case=Nom|Degree=Cmp|Gender=Fem|Number=Sing', 'head': 15, 'deprel': 'conj', 'deps': '5:ccomp|15:conj',
        'misc': 'Id=1rzm|LTranslit=biľšyj|Translit=biľša'},
       {'id': (19,), 'text': 'за', 'lemma': 'за', 'upos': 'ADP', 'xpos': 'Spsa',
        'feats': 'Case=Acc', 'head': 20, 'deprel': 'case', 'deps': '20:case',
        'misc': 'Id=1rzn|LTranslit=za|Translit=za'},
       {'id': (20,), 'text': 'решту', 'lemma': 'решта', 'upos': 'NOUN', 'xpos': 'Ncfsan',
        'feats': 'Animacy=Inan|Case=Acc|Gender=Fem|Number=Sing', 'head': 18, 'deprel': 'obl', 'deps': '18:obl',
        'misc': 'Id=1rzo|LTranslit=rešta|Translit=reštu'},
       {'id': (21,), 'text': 'тексту', 'lemma': 'текст', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 20, 'deprel': 'nmod', 'deps': '20:nmod',
        'misc': 'Id=1rzp|LTranslit=tekst|Translit=tekstu'},
       {'id': (22,), 'text': 'О_о', 'lemma': 'О_о', 'upos': 'SYM', 'xpos': 'X', 'head': 2, 'deprel': 'discourse',
        'deps': '2:discourse', 'misc': 'Id=1rzq|LTranslit=O_o|Translit=O_o'}],
      ['підофігів трохи,коли побачив,що в паспорті угорськ графа"національність"жирним виділена і більша за'
       ' тексту решту О_о']],
     ["TP",
      [{'id': (1,), 'text': '—', 'lemma': '—', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Dash', 'head': 2,
        'deprel': 'punct', 'deps': '2:punct', 'misc': 'Id=02ub|LTranslit=—|Translit=—'},
       {'id': (2,), 'text': 'Було', 'lemma': 'бути', 'upos': 'VERB', 'xpos': 'Vapis-sn', 'feats':
        'Aspect=Imp|Gender=Neut|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=02uc|LTranslit=buty|Translit=Bulo'},
       {'id': (3,), 'text': 'трохи', 'lemma': 'трохи', 'upos': 'ADV', 'xpos': 'R', 'head': 2, 'deprel': 'advmod',
        'deps': '2:advmod', 'misc': 'Id=02ud|LTranslit=trochy|SpaceAfter=No|Translit=trochy'},
       {'id': (4,), 'text': '…', 'lemma': '…', 'upos': 'PUNCT', 'xpos': 'U', 'head': 2, 'deprel': 'punct',
        'deps': '2:punct', 'misc': 'Id=02ue|LTranslit=…|Translit=…'}],
      ["— Трохи було…"]],
     ["TP",
      [{'id': (1,), 'text': 'Київська', 'lemma': 'київський', 'upos': 'ADJ', 'xpos': 'Ao-fsns',
        'feats': 'Case=Nom|Gender=Fem|Number=Sing', 'head': 2, 'deprel': 'amod', 'deps': '2:amod',
        'misc': 'Id=1yts|LTranslit=kyjivśkyj|Translit=Kyjivśka'},
       {'id': (2,), 'text': 'ОДА', 'lemma': 'ОДА', 'upos': 'NOUN', 'xpos': 'Y',
        'feats': 'Abbr=Yes|Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 3, 'deprel': 'nsubj',
        'deps': '3:nsubj|6:nsubj:sp', 'misc': 'Id=1ytt|LTranslit=ODA|Translit=ODA'},
       {'id': (3,), 'text': 'виявилася', 'lemma': 'виявитися', 'upos': 'VERB', 'xpos': 'Vmeis-sf',
        'feats': 'Aspect=Perf|Gender=Fem|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=1ytu|LTranslit=vyjavytyśа|Translit=vyjavylaśа'},
       {'id': (4,), 'text': 'чи', 'lemma': 'чи', 'upos': 'PART', 'xpos': 'Q', 'head': 6, 'deprel': 'discourse',
        'deps': '6:discourse', 'misc': 'Id=1ytv|LTranslit=čy|Translit=čy'},
       {'id': (5,), 'text': 'не', 'lemma': 'не', 'upos': 'PART', 'xpos': 'Q', 'feats': 'Polarity=Neg', 'head': 6,
        'deprel': 'advmod', 'deps': '6:advmod', 'misc': 'Id=1ytw|LTranslit=ne|Translit=ne'},
       {'id': (6,), 'text': 'першою', 'lemma': 'перший', 'upos': 'ADJ', 'xpos': 'Mlofsi',
        'feats': 'Case=Ins|Degree=Pos|Gender=Fem|Number=Sing|NumType=Ord', 'head': 3, 'deprel': 'xcomp:sp',
        'deps': '3:xcomp:sp|9:nsubj:rel|10:nsubj:x',
        'misc': 'Id=1ytx|LTranslit=peršyj|Promoted=Yes|SpaceAfter=No|Translit=peršoju'},
       {'id': (7,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 9, 'deprel': 'punct',
        'deps': '9:punct', 'misc': 'Id=1yty|LTranslit=,|Translit=,'},
       {'id': (8,), 'text': 'яка', 'lemma': 'який', 'upos': 'DET', 'xpos': 'Pr--f-sna',
        'feats': 'Case=Nom|Gender=Fem|Number=Sing|PronType=Rel', 'head': 9, 'deprel': 'nsubj',
        'deps': '6:ref|9:nsubj|10:nsubj:x', 'misc': 'Id=1ytz|LTranslit=jakyj|Translit=jaka'},
       {'id': (9,), 'text': 'намагалася', 'lemma': 'намагатися', 'upos': 'VERB', 'xpos': 'Vmpis-sf',
        'feats': 'Aspect=Imp|Gender=Fem|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 6, 'deprel': 'acl:relcl',
        'deps': '6:acl:relcl', 'misc': 'Id=1yu0|LTranslit=namahatyśа|Translit=namahalaśа'},
       {'id': (10,), 'text': 'вплинути', 'lemma': 'вплинути', 'upos': 'VERB', 'xpos': 'Vmen',
        'feats': 'Aspect=Perf|VerbForm=Inf', 'head': 9, 'deprel': 'xcomp', 'deps': '9:xcomp',
        'misc': 'Id=1yu1|LTranslit=vplynuty|Translit=vplynuty'},
       {'id': (11,), 'text': 'на', 'lemma': 'на', 'upos': 'ADP', 'xpos': 'Spsa', 'feats': 'Case=Acc', 'head': 12,
        'deprel': 'case', 'deps': '12:case', 'misc': 'Id=1yu2|LTranslit=na|Translit=na'},
       {'id': (12,), 'text': 'перевізників', 'lemma': 'перевізник', 'upos': 'NOUN', 'xpos': 'Ncmpay',
        'feats': 'Animacy=Anim|Case=Acc|Gender=Masc|Number=Plur', 'head': 10, 'deprel': 'obl', 'deps': '10:obl',
        'misc': 'Id=1yu3|LTranslit=pereviznyk|SpaceAfter=No|Translit=pereviznykiv'},
       {'id': (13,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 3, 'deprel': 'punct',
        'deps': '3:punct', 'misc': 'Id=1yu4|LTranslit=.|Translit=.'}],
      ["ОДА Київська виявилася чи не першою, яка намагалася вплинути на перевізників."]],
     ["TP",
      [{'id': (1,), 'text': 'Тимченкова', 'lemma': 'Тимченків', 'upos': 'ADJ', 'xpos': 'Afpfsns',
        'feats': 'Case=Nom|Degree=Pos|Gender=Fem|Number=Sing', 'head': 2, 'deprel': 'amod', 'deps': '2:amod',
        'misc': 'Id=1byt|LTranslit=Tymčenkiv|Translit=Tymčenkova'},
       {'id': (2,), 'text': 'книжка', 'lemma': 'книжка', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 13, 'deprel': 'nsubj',
        'deps': '10:obl:rel|13:nsubj', 'misc': 'Id=1byu|LTranslit=knyžka|SpaceAfter=No|Translit=knyžka'},
       {'id': (3,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 10, 'deprel': 'punct',
        'deps': '10:punct', 'misc': 'Id=1byv|LTranslit=,|Translit=,'},
       {'id': (4,), 'text': 'що', 'lemma': 'що', 'upos': 'SCONJ', 'xpos': 'Css', 'head': 10, 'deprel': 'mark',
        'deps': '10:mark', 'misc': 'Id=1byw|LTranslit=ščo|Translit=ščo'},
       {'id': (5,), 'text': 'в', 'lemma': 'в', 'upos': 'ADP', 'xpos': 'Spsl', 'feats': 'Case=Loc', 'head': 6,
        'deprel': 'case', 'deps': '6:case', 'misc': 'Id=1byx|LTranslit=v|Translit=v'},
       {'id': (6,), 'text': 'ній', 'lemma': 'вона', 'upos': 'PRON', 'xpos': 'Pp-3f-sln',
        'feats': 'Case=Loc|Gender=Fem|Number=Sing|Person=3|PronType=Prs', 'head': 10, 'deprel': 'obl',
        'deps': '2:ref|10:obl', 'misc': 'Id=1byy|LTranslit=vona|Translit=nij'},
       {'id': (7,), 'text': 'близько', 'lemma': 'близько', 'upos': 'ADP', 'xpos': 'Spsg', 'feats': 'Case=Gen',
        'head': 8, 'deprel': 'case', 'deps': '8:case', 'misc': 'Id=1byz|LTranslit=blyźko|Translit=blyźko'},
       {'id': (8,), 'text': '70', 'lemma': '70', 'upos': 'NUM', 'xpos': 'Mlc-g',
        'feats': 'Case=Gen|NumType=Card|Uninflect=Yes', 'head': 9, 'deprel': 'nummod', 'deps': '9:nummod',
        'misc': 'Id=1bz0|LTranslit=70|Translit=70'},
       {'id': (9,), 'text': 'сторінок', 'lemma': 'сторінка', 'upos': 'NOUN', 'xpos': 'Ncfpgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Plur', 'head': 10, 'deprel': 'obj', 'deps': '10:obj',
        'misc': 'Id=1bz1|LTranslit=storinka|Translit=storinok'},
       {'id': (10,), 'text': 'відведено', 'lemma': 'відвести', 'upos': 'VERB', 'xpos': 'Vmeo',
        'feats': 'Aspect=Perf|Mood=Ind|Person=0|VerbForm=Fin', 'head': 2, 'deprel': 'acl:relcl', 'deps': '2:acl:relcl',
        'misc': 'Id=1bz2|LTranslit=vidvesty|Translit=vidvedeno'},
       {'id': (11,), 'text': 'фонології', 'lemma': 'фонологія', 'upos': 'NOUN', 'xpos': 'Ncfsdn',
        'feats': 'Animacy=Inan|Case=Dat|Gender=Fem|Number=Sing', 'head': 10, 'deprel': 'iobj', 'deps': '10:iobj',
        'misc': 'Id=1bz3|LTranslit=fonolohija|SpaceAfter=No|Translit=fonolohiji'},
       {'id': (12,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 10, 'deprel': 'punct',
        'deps': '10:punct', 'misc': 'Id=1bz4|LTranslit=,|Translit=,'},
       {'id': (13,), 'text': 'відзначалася', 'lemma': 'відзначатися', 'upos': 'VERB', 'xpos': 'Vmpis-sf',
        'feats': 'Aspect=Imp|Gender=Fem|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=1bz5|LTranslit=vidznačatyśа|Translit=vidznačalaśа'},
       {'id': (14,), 'text': 'атомістичним', 'lemma': 'атомістичний', 'upos': 'ADJ', 'xpos': 'Ao-msif',
        'feats': 'Case=Ins|Gender=Masc|Number=Sing', 'head': 15, 'deprel': 'amod', 'deps': '15:amod',
        'misc': 'Id=1bz6|LTranslit=atomistyčnyj|Translit=atomistyčnym'},
       {'id': (15,), 'text': 'викладом', 'lemma': 'виклад', 'upos': 'NOUN', 'xpos': 'Ncmsin',
        'feats': 'Animacy=Inan|Case=Ins|Gender=Masc|Number=Sing', 'head': 13, 'deprel': 'obl', 'deps': '13:obl',
        'misc': 'Id=1bz7|LTranslit=vyklad|SpaceAfter=No|Translit=vykladom'},
       {'id': (16,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 17, 'deprel': 'punct',
        'deps': '17:punct', 'misc': 'Id=1bz8|LTranslit=,|Translit=,'},
       {'id': (17,), 'text': 'типовим', 'lemma': 'типовий', 'upos': 'ADJ', 'xpos': 'Afpmsif',
        'feats': 'Case=Ins|Degree=Pos|Gender=Masc|Number=Sing', 'head': 15, 'deprel': 'amod', 'deps': '15:amod',
        'misc': 'Id=1bz9|LTranslit=typovyj|Translit=typovym'},
       {'id': (18,), 'text': 'для', 'lemma': 'для', 'upos': 'ADP', 'xpos': 'Spsg', 'feats': 'Case=Gen', 'head': 20,
        'deprel': 'case', 'deps': '20:case', 'misc': 'Id=1bza|LTranslit=dľа|Translit=dľа'},
       {'id': (19,), 'text': 'молодограматичної', 'lemma': 'молодограматичний', 'upos': 'ADJ', 'xpos': 'Ao-fsgf',
        'feats': 'Case=Gen|Gender=Fem|Number=Sing', 'head': 20, 'deprel': 'amod', 'deps': '20:amod',
        'misc': 'Id=1bzb|LTranslit=molodohramatyčnyj|Translit=molodohramatyčnoji'},
       {'id': (20,), 'text': 'школи', 'lemma': 'школа', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 17, 'deprel': 'obl', 'deps': '17:obl',
        'misc': 'Id=1bzc|LTranslit=škola|SpaceAfter=No|Translit=školy'},
       {'id': (21,), 'text': ':', 'lemma': ':', 'upos': 'PUNCT', 'xpos': 'U', 'head': 25, 'deprel': 'punct',
        'deps': '25:punct', 'misc': 'Id=1bzd|LTranslit=:|Translit=:'},
       {'id': (22,), 'text': 'зміни', 'lemma': 'зміна', 'upos': 'NOUN', 'xpos': 'Ncfpan',
        'feats': 'Animacy=Inan|Case=Acc|Gender=Fem|Number=Plur', 'head': 25, 'deprel': 'obj', 'deps': '25:obj',
        'misc': 'Id=1bze|LTranslit=zmina|Translit=zminy'},
       {'id': (23,), 'text': 'кожного', 'lemma': 'кожний', 'upos': 'DET', 'xpos': 'Pg--m-sga',
        'feats': 'Case=Gen|Gender=Masc|Number=Sing|PronType=Tot', 'head': 24, 'deprel': 'det', 'deps': '24:det',
        'misc': 'Id=1bzf|LTranslit=kožnyj|Translit=kožnoho'},
       {'id': (24,), 'text': 'звука', 'lemma': 'звук', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 22, 'deprel': 'nmod', 'deps': '22:nmod',
        'misc': 'Id=1bzg|LTranslit=zvuk|Translit=zvuka'},
       {'id': (25,), 'text': 'представлено', 'lemma': 'представити', 'upos': 'VERB', 'xpos': 'Vmeo',
        'feats': 'Aspect=Perf|Mood=Ind|Person=0|VerbForm=Fin', 'head': 13, 'deprel': 'parataxis',
        'deps': '13:parataxis', 'misc': 'Id=1bzh|LTranslit=predstavyty|Translit=predstavleno'},
       {'id': (26,), 'text': 'в', 'lemma': 'в', 'upos': 'ADP', 'xpos': 'Spsl', 'feats': 'Case=Loc', 'head': 27,
        'deprel': 'case', 'deps': '27:case', 'misc': 'Id=1bzi|LTranslit=v|Translit=v'},
       {'id': (27,), 'text': 'ізоляції', 'lemma': 'ізоляція', 'upos': 'NOUN', 'xpos': 'Ncfsln',
        'feats': 'Animacy=Inan|Case=Loc|Gender=Fem|Number=Sing', 'head': 25, 'deprel': 'obl', 'deps': '25:obl',
        'misc': 'Id=1bzj|LTranslit=izoľаcija|Translit=izoľаciji'},
       {'id': (28,), 'text': 'від', 'lemma': 'від', 'upos': 'ADP', 'xpos': 'Spsg', 'feats': 'Case=Gen', 'head': 29,
        'deprel': 'case', 'deps': '29:case', 'misc': 'Id=1bzk|LTranslit=vid|Translit=vid'},
       {'id': (29,), 'text': 'інших', 'lemma': 'інший', 'upos': 'DET', 'xpos': 'Pi----pga',
        'feats': 'Case=Gen|Number=Plur|PronType=Ind', 'head': 27, 'deprel': 'nmod', 'deps': '27:nmod',
        'misc': 'Id=1bzl|LTranslit=inšyj|Promoted=Yes|SpaceAfter=No|Translit=inšych'},
       {'id': (30,), 'text': ';', 'lemma': ';', 'upos': 'PUNCT', 'xpos': 'U', 'head': 37, 'deprel': 'punct',
        'deps': '37:punct', 'misc': 'Id=1bzm|LTranslit=;|Translit=;'},
       {'id': (31,), 'text': 'часові', 'lemma': 'часовий', 'upos': 'ADJ', 'xpos': 'Ao--pns',
        'feats': 'Case=Nom|Number=Plur', 'head': 34, 'deprel': 'amod', 'deps': '34:amod',
        'misc': 'Id=1bzn|LTranslit=časovyj|Translit=časovi'},
       {'id': (32,), 'text': 'й', 'lemma': 'й', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 33, 'deprel': 'cc',
        'deps': '33:cc', 'misc': 'Id=1bzo|LTranslit=j|Translit=j'},
       {'id': (33,), 'text': 'територіальні', 'lemma': 'територіальний', 'upos': 'ADJ', 'xpos': 'Ao--pns',
        'feats': 'Case=Nom|Number=Plur', 'head': 31, 'deprel': 'conj', 'deps': '31:conj|34:amod',
        'misc': 'Id=1bzp|LTranslit=terytoriaľnyj|Translit=terytoriaľni'},
       {'id': (34,), 'text': 'характеристики', 'lemma': 'характеристика', 'upos': 'NOUN', 'xpos': 'Ncfpnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Plur', 'head': 37, 'deprel': 'nsubj', 'deps': '37:nsubj',
        'misc': 'Id=1bzq|LTranslit=charakterystyka|Translit=charakterystyky'},
       {'id': (35,), 'text': 'майже', 'lemma': 'майже', 'upos': 'ADV', 'xpos': 'R', 'head': 36, 'deprel': 'advmod',
        'deps': '36:advmod', 'misc': 'Id=1bzr|LTranslit=majže|Translit=majže'},
       {'id': (36,), 'text': 'не', 'lemma': 'не', 'upos': 'PART', 'xpos': 'Q', 'feats': 'Polarity=Neg', 'head': 37,
        'deprel': 'advmod', 'deps': '37:advmod', 'misc': 'Id=1bzs|LTranslit=ne|Translit=ne'},
       {'id': (37,), 'text': 'враховуються', 'lemma': 'враховуватися', 'upos': 'VERB', 'xpos': 'Vmpip3p',
        'feats': 'Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'head': 25, 'deprel': 'parataxis',
        'deps': '25:parataxis', 'misc': 'Id=1bzt|LTranslit=vrachovuvatyśа|SpaceAfter=No|Translit=vrachovujuťśа'},
       {'id': (38,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 44, 'deprel': 'punct',
        'deps': '44:punct', 'misc': 'Id=1bzu|LTranslit=,|Translit=,'},
       {'id': (39,), 'text': 'нечисленні', 'lemma': 'нечисленний', 'upos': 'ADJ', 'xpos': 'Ao--pns',
        'feats': 'Case=Nom|Number=Plur', 'head': 40, 'deprel': 'amod', 'deps': '40:amod',
        'misc': 'Id=1bzv|LTranslit=nečyslennyj|Translit=nečyslenni'},
       {'id': (40,), 'text': 'спроби', 'lemma': 'спроба', 'upos': 'NOUN', 'xpos': 'Ncfpnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Plur', 'head': 44, 'deprel': 'nsubj', 'deps': '44:nsubj',
        'misc': 'Id=1bzw|LTranslit=sproba|Translit=sproby'},
       {'id': (41,), 'text': 'хронологічного', 'lemma': 'хронологічний', 'upos': 'ADJ', 'xpos': 'Ao-msgf',
        'feats': 'Case=Gen|Gender=Masc|Number=Sing', 'head': 42, 'deprel': 'amod', 'deps': '42:amod',
        'misc': 'Id=1bzx|LTranslit=chronolohičnyj|Translit=chronolohičnoho'},
       {'id': (42,), 'text': 'аналізу', 'lemma': 'аналіз', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 40, 'deprel': 'nmod', 'deps': '40:nmod',
        'misc': 'Id=1bzy|LTranslit=analiz|Translit=analizu'},
       {'id': (43,), 'text': 'є', 'lemma': 'бути', 'upos': 'AUX', 'xpos': 'Vapip3p',
        'feats': 'Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'head': 44, 'deprel': 'cop',
        'deps': '44:cop', 'misc': 'Id=1bzz|LTranslit=buty|Translit=ě'},
       {'id': (44,), 'text': 'непевними', 'lemma': 'непевний', 'upos': 'ADJ', 'xpos': 'Ao--pif',
        'feats': 'Case=Ins|Number=Plur', 'head': 25, 'deprel': 'parataxis', 'deps': '25:parataxis',
        'misc': 'Id=1c00|LTranslit=nepevnyj|Translit=nepevnymy'},
       {'id': (45,), 'text': 'через', 'lemma': 'через', 'upos': 'ADP', 'xpos': 'Spsa', 'feats': 'Case=Acc', 'head': 46,
        'deprel': 'case', 'deps': '46:case', 'misc': 'Id=1c01|LTranslit=čerez|Translit=čerez'},
       {'id': (46,), 'text': 'брак', 'lemma': 'брак', 'upos': 'NOUN', 'xpos': 'Ncmsan',
        'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Sing', 'head': 44, 'deprel': 'obl', 'deps': '44:obl',
        'misc': 'Id=1c02|LTranslit=brak|Translit=brak'},
       {'id': (47,), 'text': 'критичного', 'lemma': 'критичний', 'upos': 'ADJ', 'xpos': 'Afpmsgf',
        'feats': 'Case=Gen|Degree=Pos|Gender=Masc|Number=Sing', 'head': 48, 'deprel': 'amod', 'deps': '48:amod',
        'misc': 'Id=1c03|LTranslit=krytyčnyj|Translit=krytyčnoho'},
       {'id': (48,), 'text': 'підходу', 'lemma': 'підхід', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 46, 'deprel': 'nmod', 'deps': '46:nmod',
        'misc': 'Id=1c04|LTranslit=pidchid|Translit=pidchodu'},
       {'id': (49,), 'text': 'до', 'lemma': 'до', 'upos': 'ADP', 'xpos': 'Spsg', 'feats': 'Case=Gen', 'head': 50,
        'deprel': 'case', 'deps': '50:case', 'misc': 'Id=1c05|LTranslit=do|Translit=do'},
       {'id': (50,), 'text': 'матеріалу', 'lemma': 'матеріал', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 48, 'deprel': 'nmod', 'deps': '48:nmod',
        'misc': 'Id=1c06|LTranslit=material|Translit=materialu'},
       {'id': (51,), 'text': 'пам’яток', 'lemma': 'пам’ятка', 'upos': 'NOUN', 'xpos': 'Ncfpgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Plur', 'head': 50, 'deprel': 'nmod', 'deps': '50:nmod',
        'misc': 'Id=1c07|LTranslit=pamjatka|SpaceAfter=No|Translit=pamjatok'},
       {'id': (52,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 13, 'deprel': 'punct',
        'deps': '13:punct', 'misc': 'Id=1c08|LTranslit=.|Translit=.'}],
      ["Книжка Тимченкова, що в ній близько 70 сторінок відведено фонології, відзначалася викладом атомістичним,"
       " типовим для школи молодограматичної: зміни кожного звука представлено в ізоляції від інших; часові й "
       "територіальні характеристики майже не враховуються, спроби нечисленні аналізу хронологічного є непевними "
       "через брак підходу критичного до пам’яток матеріалу."]],
     ["TP",
      [{'id': (1,), 'text': 'Справа', 'lemma': 'справа', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 16, 'deprel': 'nsubj', 'deps': '16:nsubj',
        'misc': 'Id=29gy|LTranslit=sprava|Translit=Sprava'},
       {'id': (2,), 'text': '31', 'lemma': '31', 'upos': 'ADJ', 'xpos': 'Mlonsg',
        'feats': 'Case=Gen|Gender=Neut|Number=Sing|NumType=Ord|Uninflect=Yes', 'head': 1, 'deprel': 'nmod',
        'deps': '1:nmod', 'misc': 'Id=29gz|LTranslit=31|Promoted=Yes|Translit=31'},
       {'id': (3,), 'text': 'серпня', 'lemma': 'серпень', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 2, 'deprel': 'nmod', 'deps': '2:nmod',
        'misc': 'Id=29h0|LTranslit=serpeń|Translit=serpńа'},
       {'id': (4,), 'text': '(', 'lemma': '(', 'upos': 'PUNCT', 'xpos': 'U', 'head': 6, 'deprel': 'punct',
        'deps': '6:punct', 'misc': 'Id=29h1|LTranslit=(|SpaceAfter=No|Translit=('},
       {'id': (5,), 'text': 'Масові', 'lemma': 'масовий', 'upos': 'ADJ', 'xpos': 'Afp-pns',
        'feats': 'Case=Nom|Degree=Pos|Number=Plur', 'head': 6, 'deprel': 'amod', 'deps': '6:amod',
        'misc': 'Id=29h2|LTranslit=masovyj|Translit=Masovi'},
       {'id': (6,), 'text': 'заворушення', 'lemma': 'заворушення', 'upos': 'NOUN', 'xpos': 'Ncnpnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Neut|Number=Plur', 'head': 1, 'deprel': 'appos', 'deps': '1:appos',
        'misc': 'Id=29h3|LTranslit=zavorušenńа|Translit=zavorušenńа'},
       {'id': (7,), 'text': '31', 'lemma': '31', 'upos': 'ADJ', 'xpos': 'Mlonsg',
        'feats': 'Case=Gen|Gender=Neut|Number=Sing|NumType=Ord|Uninflect=Yes', 'head': 6, 'deprel': 'nmod',
        'deps': '6:nmod', 'misc': 'Id=29h4|LTranslit=31|Promoted=Yes|Translit=31'},
       {'id': (8,), 'text': 'серпня', 'lemma': 'серпень', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 7, 'deprel': 'nmod', 'deps': '7:nmod',
        'misc': 'Id=29h5|LTranslit=serpeń|SpaceAfter=No|Translit=serpńа'},
       {'id': (9,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 10, 'deprel': 'punct',
        'deps': '10:punct', 'misc': 'Id=29h6|LTranslit=,|Translit=,'},
       {'id': (10,), 'text': 'Справа', 'lemma': 'справа', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 6, 'deprel': 'conj', 'deps': '1:appos|6:conj',
        'misc': 'Id=29h7|LTranslit=sprava|Translit=Sprava'},
       {'id': (11,), 'text': 'захисників', 'lemma': 'захисник', 'upos': 'NOUN', 'xpos': 'Ncmpgy',
        'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Plur', 'head': 10, 'deprel': 'nmod', 'deps': '10:nmod',
        'misc': 'Id=29h8|LTranslit=zachysnyk|Translit=zachysnykiv'},
       {'id': (12,), 'text': 'Конституції', 'lemma': 'конституція', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 11, 'deprel': 'nmod', 'deps': '11:nmod',
        'misc': 'Id=29h9|LTranslit=konstytucija|SpaceAfter=No|Translit=Konstytuciji'},
       {'id': (13,), 'text': ')', 'lemma': ')', 'upos': 'PUNCT', 'xpos': 'U', 'head': 6, 'deprel': 'punct',
        'deps': '6:punct', 'misc': 'Id=29ha|LTranslit=)|Translit=)'},
       {'id': (14,), 'text': '—', 'lemma': '—', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Dash', 'head': 16,
        'deprel': 'punct', 'deps': '16:punct', 'misc': 'Id=29hb|LTranslit=—|Translit=—'},
       {'id': (15,), 'text': 'кримінальне', 'lemma': 'кримінальний', 'upos': 'ADJ', 'xpos': 'Ao-nsns',
        'feats': 'Case=Nom|Gender=Neut|Number=Sing', 'head': 16, 'deprel': 'amod', 'deps': '16:amod',
        'misc': 'Id=29hc|LTranslit=kryminaľnyj|Translit=kryminaľne'},
       {'id': (16,), 'text': 'провадження', 'lemma': 'провадження', 'upos': 'NOUN', 'xpos': 'Ncnsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Neut|Number=Sing', 'head': 0, 'deprel': 'root',
        'deps': '0:root|19:nsubj:rel', 'misc': 'Id=29hd|LTranslit=provadženńа|SpaceAfter=No|Translit=provadženńа'},
       {'id': (17,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 19, 'deprel': 'punct',
        'deps': '19:punct', 'misc': 'Id=29he|LTranslit=,|Translit=,'},
       {'id': (18,), 'text': 'яке', 'lemma': 'який', 'upos': 'DET', 'xpos': 'Pr--n-sna',
        'feats': 'Case=Nom|Gender=Neut|Number=Sing|PronType=Rel', 'head': 19, 'deprel': 'nsubj',
        'deps': '16:ref|19:nsubj', 'misc': 'Id=29hf|LTranslit=jakyj|Translit=jake'},
       {'id': (19,), 'text': 'розслідується', 'lemma': 'розслідуватися', 'upos': 'VERB', 'xpos': 'Vmpip3s',
        'feats': 'Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'head': 16, 'deprel': 'acl:relcl',
        'deps': '16:acl:relcl', 'misc': 'Id=29hg|LTranslit=rozsliduvatyśа|Translit=rozsliduěťśа'},
       {'id': (20,), 'text': 'Національною', 'lemma': 'національний', 'upos': 'ADJ', 'xpos': 'Ao-fsif',
        'feats': 'Case=Ins|Gender=Fem|Number=Sing', 'head': 21, 'deprel': 'amod', 'deps': '21:amod',
        'misc': 'Id=29hh|LTranslit=nacionaľnyj|Translit=Nacionaľnoju'},
       {'id': (21,), 'text': 'поліцією', 'lemma': 'поліція', 'upos': 'NOUN', 'xpos': 'Ncfsin',
        'feats': 'Animacy=Inan|Case=Ins|Gender=Fem|Number=Sing', 'head': 19, 'deprel': 'obl', 'deps': '19:obl',
        'misc': 'Id=29hi|LTranslit=policija|SpaceAfter=No|Translit=policiěju'},
       {'id': (22,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 23, 'deprel': 'punct',
        'deps': '23:punct', 'misc': 'Id=29hj|LTranslit=,|Translit=,'},
       {'id': (23,), 'text': 'Службою', 'lemma': 'служба', 'upos': 'NOUN', 'xpos': 'Ncfsin',
        'feats': 'Animacy=Inan|Case=Ins|Gender=Fem|Number=Sing', 'head': 21, 'deprel': 'conj', 'deps': '19:obl|21:conj',
        'misc': 'Id=29hk|LTranslit=služba|Translit=Služboju'},
       {'id': (24,), 'text': 'безпеки', 'lemma': 'безпека', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 23, 'deprel': 'nmod', 'deps': '23:nmod',
        'misc': 'Id=29hl|LTranslit=bezpeka|Translit=bezpeky'},
       {'id': (25,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 27, 'deprel': 'cc',
        'deps': '27:cc', 'misc': 'Id=29hm|LTranslit=ta|Translit=ta'},
       {'id': (26,), 'text': 'Генеральною', 'lemma': 'генеральний', 'upos': 'ADJ', 'xpos': 'Ao-fsif',
        'feats': 'Case=Ins|Gender=Fem|Number=Sing', 'head': 27, 'deprel': 'amod', 'deps': '27:amod',
        'misc': 'Id=29hn|LTranslit=heneraľnyj|Translit=Heneraľnoju'},
       {'id': (27,), 'text': 'прокуратурою', 'lemma': 'прокуратура', 'upos': 'NOUN', 'xpos': 'Ncfsin',
        'feats': 'Animacy=Inan|Case=Ins|Gender=Fem|Number=Sing', 'head': 21, 'deprel': 'conj', 'deps': '19:obl|21:conj',
        'misc': 'Id=29ho|LTranslit=prokuratura|Translit=prokuraturoju'},
       {'id': (28,), 'text': 'України', 'lemma': 'Україна', 'upos': 'PROPN', 'xpos': 'Npfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 27, 'deprel': 'nmod', 'deps': '27:nmod',
        'misc': 'Id=29hp|LTranslit=Ukrajina|Translit=Ukrajiny'},
       {'id': (29,), 'text': 'за', 'lemma': 'за', 'upos': 'ADP', 'xpos': 'Spsi', 'feats': 'Case=Ins', 'head': 30,
        'deprel': 'case', 'deps': '30:case', 'misc': 'Id=29hq|LTranslit=za|Translit=za'},
       {'id': (30,), 'text': 'фактом', 'lemma': 'факт', 'upos': 'NOUN', 'xpos': 'Ncmsin',
        'feats': 'Animacy=Inan|Case=Ins|Gender=Masc|Number=Sing', 'head': 19, 'deprel': 'obl', 'deps': '19:obl',
        'misc': 'Id=29hr|LTranslit=fakt|Translit=faktom'},
       {'id': (31,), 'text': 'масових', 'lemma': 'масовий', 'upos': 'ADJ', 'xpos': 'Afp-pgf',
        'feats': 'Case=Gen|Degree=Pos|Number=Plur', 'head': 32, 'deprel': 'amod', 'deps': '32:amod',
        'misc': 'Id=29hs|LTranslit=masovyj|Translit=masovych'},
       {'id': (32,), 'text': 'заворушень', 'lemma': 'заворушення', 'upos': 'NOUN', 'xpos': 'Ncnpgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Neut|Number=Plur', 'head': 30, 'deprel': 'nmod', 'deps': '30:nmod',
        'misc': 'Id=29ht|LTranslit=zavorušenńа|SpaceAfter=No|Translit=zavorušeń'},
       {'id': (33,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 34, 'deprel': 'punct',
        'deps': '34:punct', 'misc': 'Id=29hu|LTranslit=,|Translit=,'},
       {'id': (34,), 'text': 'поєднаних', 'lemma': 'поєднаний', 'upos': 'ADJ', 'xpos': 'Ap--pgf-ep',
        'feats': 'Aspect=Perf|Case=Gen|Number=Plur|VerbForm=Part|Voice=Pass', 'head': 32, 'deprel': 'amod',
        'deps': '32:amod', 'misc': 'Id=29hv|LTranslit=poědnanyj|Translit=poědnanych'},
       {'id': (35,), 'text': 'із', 'lemma': 'із', 'upos': 'ADP', 'xpos': 'Spsi', 'feats': 'Case=Ins', 'head': 36,
        'deprel': 'case', 'deps': '36:case', 'misc': 'Id=29hw|LTranslit=iz|Translit=iz'},
       {'id': (36,), 'text': 'нанесенням', 'lemma': 'нанесення', 'upos': 'NOUN', 'xpos': 'Ncnsin',
        'feats': 'Animacy=Inan|Case=Ins|Gender=Neut|Number=Sing', 'head': 34, 'deprel': 'obl', 'deps': '34:obl',
        'misc': 'Id=29hx|LTranslit=nanesenńа|Translit=nanesenńаm'},
       {'id': (37,), 'text': 'тілесних', 'lemma': 'тілесний', 'upos': 'ADJ', 'xpos': 'Ao--pgf',
        'feats': 'Case=Gen|Number=Plur', 'head': 38, 'deprel': 'amod', 'deps': '38:amod',
        'misc': 'Id=29hy|LTranslit=tilesnyj|Translit=tilesnych'},
       {'id': (38,), 'text': 'ушкоджень', 'lemma': 'ушкодження', 'upos': 'NOUN', 'xpos': 'Ncnpgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Neut|Number=Plur', 'head': 36, 'deprel': 'nmod', 'deps': '36:nmod',
        'misc': 'Id=29hz|LTranslit=uškodženńа|Translit=uškodžeń'},
       {'id': (39,), 'text': 'працівникам', 'lemma': 'працівник', 'upos': 'NOUN', 'xpos': 'Ncmpdy',
        'feats': 'Animacy=Anim|Case=Dat|Gender=Masc|Number=Plur', 'head': 36, 'deprel': 'nmod', 'deps': '36:nmod',
        'misc': 'Id=29i0|LTranslit=pracivnyk|Translit=pracivnykam'},
       {'id': (40,), 'text': 'міліції', 'lemma': 'міліція', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 39, 'deprel': 'nmod', 'deps': '39:nmod',
        'misc': 'Id=29i1|LTranslit=milicija|Translit=miliciji'},
       {'id': (41,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 42, 'deprel': 'cc',
        'deps': '42:cc', 'misc': 'Id=29i2|LTranslit=ta|Translit=ta'},
       {'id': (42,), 'text': 'військовослужбовцям', 'lemma': 'військовослужбовець', 'upos': 'NOUN', 'xpos': 'Ncmpdy',
        'feats': 'Animacy=Anim|Case=Dat|Gender=Masc|Number=Plur', 'head': 39, 'deprel': 'conj',
        'deps': '36:nmod|39:conj', 'misc': 'Id=29i3|LTranslit=vijśkovoslužboveć|Translit=vijśkovoslužbovćаm'},
       {'id': (43,), 'text': 'Національної', 'lemma': 'національний', 'upos': 'ADJ', 'xpos': 'Ao-fsgf',
        'feats': 'Case=Gen|Gender=Fem|Number=Sing', 'head': 44, 'deprel': 'amod', 'deps': '44:amod',
        'misc': 'Id=29i4|LTranslit=nacionaľnyj|Translit=Nacionaľnoji'},
       {'id': (44,), 'text': 'гвардії', 'lemma': 'гвардія', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 42, 'deprel': 'nmod', 'deps': '42:nmod',
        'misc': 'Id=29i5|LTranslit=hvardija|Translit=hvardiji'},
       {'id': (45,), 'text': 'України', 'lemma': 'Україна', 'upos': 'PROPN', 'xpos': 'Npfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 44, 'deprel': 'nmod', 'deps': '44:nmod',
        'misc': 'Id=29i6|LTranslit=Ukrajina|SpaceAfter=No|Translit=Ukrajiny'},
       {'id': (46,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 49, 'deprel': 'punct',
        'deps': '49:punct', 'misc': 'Id=29i7|LTranslit=,|Translit=,'},
       {'id': (47,), 'text': 'а', 'lemma': 'а', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 49, 'deprel': 'cc',
        'deps': '49:cc', 'misc': 'Id=29i8|LTranslit=a|Translit=a'},
       {'id': (48,), 'text': 'також', 'lemma': 'також', 'upos': 'ADV', 'xpos': 'R', 'head': 47, 'deprel': 'fixed',
        'deps': '47:fixed', 'misc': 'Id=29i9|LTranslit=takož|Translit=takož'},
       {'id': (49,), 'text': 'смертей', 'lemma': 'смерть', 'upos': 'NOUN', 'xpos': 'Ncfpgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Plur', 'head': 32, 'deprel': 'conj',
        'deps': '30:nmod|32:conj', 'misc': 'Id=29ia|LTranslit=smerť|Translit=smertej'},
       {'id': (50,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 51, 'deprel': 'cc',
        'deps': '51:cc', 'misc': 'Id=29ib|LTranslit=ta|Translit=ta'},
       {'id': (51,), 'text': 'поранень', 'lemma': 'поранення', 'upos': 'NOUN', 'xpos': 'Ncnpgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Neut|Number=Plur', 'head': 49, 'deprel': 'conj',
        'deps': '30:nmod|49:conj', 'misc': 'Id=29ic|LTranslit=poranenńа|Translit=poraneń'},
       {'id': (52,), 'text': 'працівників', 'lemma': 'працівник', 'upos': 'NOUN', 'xpos': 'Ncmpgy',
        'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Plur', 'head': 49, 'deprel': 'nmod', 'deps': '49:nmod',
        'misc': 'Id=29id|LTranslit=pracivnyk|Translit=pracivnykiv'},
       {'id': (53,), 'text': 'міліції', 'lemma': 'міліція', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 52, 'deprel': 'nmod', 'deps': '52:nmod',
        'misc': 'Id=29ie|LTranslit=milicija|Translit=miliciji'},
       {'id': (54,), 'text': 'та', 'lemma': 'та', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 55, 'deprel': 'cc',
        'deps': '55:cc', 'misc': 'Id=29if|LTranslit=ta|Translit=ta'},
       {'id': (55,), 'text': 'військовослужбовців', 'lemma': 'військовослужбовець', 'upos': 'NOUN', 'xpos': 'Ncmpgy',
        'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Plur', 'head': 52, 'deprel': 'conj',
        'deps': '49:nmod|52:conj', 'misc': 'Id=29ig|LTranslit=vijśkovoslužboveć|Translit=vijśkovoslužbovciv'},
       {'id': (56,), 'text': 'Національної', 'lemma': 'національний', 'upos': 'ADJ', 'xpos': 'Ao-fsgf',
        'feats': 'Case=Gen|Gender=Fem|Number=Sing', 'head': 57, 'deprel': 'amod', 'deps': '57:amod',
        'misc': 'Id=29ih|LTranslit=nacionaľnyj|Translit=Nacionaľnoji'},
       {'id': (57,), 'text': 'гвардії', 'lemma': 'гвардія', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 55, 'deprel': 'nmod', 'deps': '55:nmod',
        'misc': 'Id=29ii|LTranslit=hvardija|Translit=hvardiji'},
       {'id': (58,), 'text': 'України', 'lemma': 'Україна', 'upos': 'PROPN', 'xpos': 'Npfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 57, 'deprel': 'nmod', 'deps': '57:nmod',
        'misc': 'Id=29ij|LTranslit=Ukrajina|Translit=Ukrajiny'},
       {'id': (59,), 'text': 'в', 'lemma': 'в', 'upos': 'ADP', 'xpos': 'Spsl', 'feats': 'Case=Loc', 'head': 60,
        'deprel': 'case', 'deps': '60:case', 'misc': 'Id=29ik|LTranslit=v|Translit=v'},
       {'id': (60,), 'text': 'результаті', 'lemma': 'результат', 'upos': 'NOUN', 'xpos': 'Ncmsln',
        'feats': 'Animacy=Inan|Case=Loc|Gender=Masc|Number=Sing', 'head': 49, 'deprel': 'nmod', 'deps': '49:nmod',
        'misc': 'Id=29il|LTranslit=rezuľtat|Translit=rezuľtati'},
       {'id': (61,), 'text': 'метання', 'lemma': 'метання', 'upos': 'NOUN', 'xpos': 'Ncnsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Neut|Number=Sing', 'head': 60, 'deprel': 'nmod', 'deps': '60:nmod',
        'misc': 'Id=29im|LTranslit=metanńа|SpaceAfter=No|Translit=metanńа'},
       {'id': (62,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 64, 'deprel': 'punct',
        'deps': '64:punct', 'misc': 'Id=29in|LTranslit=,|Translit=,'},
       {'id': (63,), 'text': 'за', 'lemma': 'за', 'upos': 'ADP', 'xpos': 'Spsi', 'feats': 'Case=Ins', 'head': 64,
        'deprel': 'case', 'deps': '64:case', 'misc': 'Id=29io|LTranslit=za|Translit=za'},
       {'id': (64,), 'text': 'версією', 'lemma': 'версія', 'upos': 'NOUN', 'xpos': 'Ncfsin',
        'feats': 'Animacy=Inan|Case=Ins|Gender=Fem|Number=Sing', 'head': 68, 'deprel': 'parataxis',
        'deps': '68:parataxis', 'misc': 'Id=29ip|LTranslit=versija|Translit=versiěju'},
       {'id': (65,), 'text': 'української', 'lemma': 'український', 'upos': 'ADJ', 'xpos': 'Ao-fsgf',
        'feats': 'Case=Gen|Gender=Fem|Number=Sing', 'head': 66, 'deprel': 'amod', 'deps': '66:amod',
        'misc': 'Id=29iq|LTranslit=ukrajinśkyj|Translit=ukrajinśkoji'},
       {'id': (66,), 'text': 'влади', 'lemma': 'влада', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 64, 'deprel': 'nmod', 'deps': '64:nmod',
        'misc': 'Id=29ir|LTranslit=vlada|SpaceAfter=No|Translit=vlady'},
       {'id': (67,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 64, 'deprel': 'punct',
        'deps': '64:punct', 'misc': 'Id=29is|LTranslit=,|Translit=,'},
       {'id': (68,), 'text': 'гранати', 'lemma': 'граната', 'upos': 'NOUN', 'xpos': 'Ncfsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Sing', 'head': 61, 'deprel': 'nmod', 'deps': '61:nmod',
        'misc': 'Id=29it|LTranslit=hranata|Translit=hranaty'},
       {'id': (69,), 'text': 'РГО', 'lemma': 'РГО', 'upos': 'NOUN', 'xpos': 'Y',
        'feats': 'Abbr=Yes|Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing|Uninflect=Yes', 'head': 68,
        'deprel': 'flat:title', 'deps': '68:flat:title', 'misc': 'Id=29iu|LTranslit=RHO|Translit=RHO'},
       {'id': (70,), 'text': 'з', 'lemma': 'з', 'upos': 'ADP', 'xpos': 'Spsg', 'feats': 'Case=Gen', 'head': 71,
        'deprel': 'case', 'deps': '71:case', 'misc': 'Id=29iv|LTranslit=z|Translit=z'},
       {'id': (71,), 'text': 'натовпу', 'lemma': 'натовп', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 61, 'deprel': 'nmod', 'deps': '61:nmod',
        'misc': 'Id=29iw|LTranslit=natovp|Translit=natovpu'},
       {'id': (72,), 'text': 'в', 'lemma': 'в', 'upos': 'ADP', 'xpos': 'Spsa', 'feats': 'Case=Acc', 'head': 73,
        'deprel': 'case', 'deps': '73:case', 'misc': 'Id=29ix|LTranslit=v|Translit=v'},
       {'id': (73,), 'text': 'лаву', 'lemma': 'лава', 'upos': 'NOUN', 'xpos': 'Ncfsan',
        'feats': 'Animacy=Inan|Case=Acc|Gender=Fem|Number=Sing', 'head': 61, 'deprel': 'nmod', 'deps': '61:nmod',
        'misc': 'Id=29iy|LTranslit=lava|Translit=lavu'},
       {'id': (74,), 'text': 'правоохоронців', 'lemma': 'правоохоронець', 'upos': 'NOUN', 'xpos': 'Ncmpgy',
        'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Plur', 'head': 73, 'deprel': 'nmod', 'deps': '73:nmod',
        'misc': 'Id=29iz|LTranslit=pravoochoroneć|SpaceAfter=No|Translit=pravoochoronciv'},
       {'id': (75,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 78, 'deprel': 'punct',
        'deps': '78:punct', 'misc': 'Id=29j0|LTranslit=,|Translit=,'},
       {'id': (76,), 'text': 'що', 'lemma': 'що', 'upos': 'PRON', 'xpos': 'Pr--nnsan',
        'feats': 'Animacy=Inan|Case=Acc|Gender=Neut|Number=Sing|PronType=Rel', 'head': 78, 'deprel': 'obj',
        'deps': '78:obj', 'misc': 'Id=29j1|LTranslit=ščo|Translit=ščo'},
       {'id': (77,), 'text': 'було', 'lemma': 'бути', 'upos': 'AUX', 'xpos': 'Vapis-sn',
        'feats': 'Aspect=Imp|Gender=Neut|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 78, 'deprel': 'aux',
        'deps': '78:aux', 'misc': 'Id=29j2|LTranslit=buty|Translit=bulo'},
       {'id': (78,), 'text': 'кваліфіковано', 'lemma': 'кваліфікувати', 'upos': 'VERB', 'xpos': 'Vmeo',
        'feats': 'Aspect=Perf|Mood=Ind|Person=0|VerbForm=Fin', 'head': 61, 'deprel': 'parataxis:rel',
        'deps': '61:parataxis:rel', 'misc': 'Id=29j3|LTranslit=kvalifikuvaty|Translit=kvalifikovano'},
       {'id': (79,), 'text': 'як', 'lemma': 'як', 'upos': 'SCONJ', 'xpos': 'Css', 'head': 82, 'deprel': 'mark',
        'deps': '82:mark', 'misc': 'Id=29j4|LTranslit=jak|Translit=jak'},
       {'id': (80,), 'text': 'організований', 'lemma': 'організований', 'upos': 'ADJ', 'xpos': 'Ap-msnf-ep',
        'feats': 'Aspect=Perf|Case=Nom|Degree=Pos|Gender=Masc|Number=Sing|VerbForm=Part|Voice=Pass', 'head': 82,
        'deprel': 'amod', 'deps': '82:amod', 'misc': 'Id=29j5|LTranslit=orhanizovanyj|Translit=orhanizovanyj'},
       {'id': (81,), 'text': 'терористичний', 'lemma': 'терористичний', 'upos': 'ADJ', 'xpos': 'Ao-msnf',
        'feats': 'Case=Nom|Gender=Masc|Number=Sing', 'head': 82, 'deprel': 'amod', 'deps': '82:amod',
        'misc': 'Id=29j6|LTranslit=terorystyčnyj|Translit=terorystyčnyj'},
       {'id': (82,), 'text': 'акт', 'lemma': 'акт', 'upos': 'NOUN', 'xpos': 'Ncmsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Masc|Number=Sing', 'head': 78, 'deprel': 'advcl', 'deps': '78:advcl',
        'misc': 'Id=29j7|LTranslit=akt|SpaceAfter=No|Translit=akt'},
       {'id': (83,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 16, 'deprel': 'punct',
        'deps': '16:punct', 'misc': 'Id=29j8|LTranslit=.|Translit=.'}],
      ["Справа серпня 31 (Заворушення масові серпня 31, Справа Конституції захисників) — провадження кримінальне, яке"
       " розслідується Поліцією національною, Безпеки службою та Генеральною України прокуратурою за фактом заворушень"
       " масових, поєднаних із нанесенням ушкоджень тілесних міліції працівникам та військовослужбовцям Національної"
       " України гвардії, а також смертей та поранень міліції працівників та військовослужбовців Національної України"
       " гвардії в результаті метання, за версією влади української, гранати РГО з натовпу в правоохоронців лаву, що"
       " було кваліфіковано як організований акт терористичний.",
       "Справа серпня 31 (Заворушення масові серпня 31, Справа Конституції захисників) — провадження кримінальне, яке"
       " розслідується Поліцією національною, Безпеки службою та Генеральною України прокуратурою за фактом заворушень"
       " масових, поєднаних із нанесенням ушкоджень тілесних міліції працівникам та військовослужбовцям Національної"
       " України гвардії, а також смертей та поранень міліції працівників та військовослужбовців Гвардії національної"
       " України в результаті метання, за версією влади української, гранати РГО з натовпу в правоохоронців лаву, що"
       " було кваліфіковано як організований акт терористичний.",
       "Справа серпня 31 (Заворушення масові серпня 31, Справа Конституції захисників) — провадження кримінальне, яке"
       " розслідується Поліцією національною, Безпеки службою та Генеральною України прокуратурою за фактом заворушень"
       " масових, поєднаних із нанесенням ушкоджень тілесних міліції працівникам та військовослужбовцям Гвардії "
       "національної України, а також смертей та поранень міліції працівників та військовослужбовців Національної "
       "України гвардії в результаті метання, за версією влади української, гранати РГО з натовпу в правоохоронців "
       "лаву, що було кваліфіковано як організований акт терористичний.",
       "Справа серпня 31 (Заворушення масові серпня 31, Справа Конституції захисників) — провадження кримінальне, яке"
       " розслідується Поліцією національною, Безпеки службою та Генеральною України прокуратурою за фактом заворушень "
       "масових, поєднаних із нанесенням ушкоджень тілесних міліції працівникам та військовослужбовцям Гвардії "
       "національної України, а також смертей та поранень міліції працівників та військовослужбовців Гвардії "
       "національної України в результаті метання, за версією влади української, гранати РГО з натовпу в правоохоронців"
       " лаву, що було кваліфіковано як організований акт терористичний.",
       "Справа серпня 31 (Заворушення масові серпня 31, Справа Конституції захисників) — провадження кримінальне, яке"
       " розслідується Поліцією національною, Безпеки службою та Прокуратурою генеральною України за фактом заворушень"
       " масових, поєднаних із нанесенням ушкоджень тілесних міліції працівникам та військовослужбовцям Національної "
       "України гвардії, а також смертей та поранень міліції працівників та військовослужбовців Національної України "
       "гвардії в результаті метання, за версією влади української, гранати РГО з натовпу в правоохоронців лаву, що "
       "було кваліфіковано як організований акт терористичний.",
       "Справа серпня 31 (Заворушення масові серпня 31, Справа Конституції захисників) — провадження кримінальне, яке"
       " розслідується Поліцією національною, Безпеки службою та Прокуратурою генеральною України за фактом заворушень"
       " масових, поєднаних із нанесенням ушкоджень тілесних міліції працівникам та військовослужбовцям Національної "
       "України гвардії, а також смертей та поранень міліції працівників та військовослужбовців Гвардії національної "
       "України в результаті метання, за версією влади української, гранати РГО з натовпу в правоохоронців лаву, що "
       "було кваліфіковано як організований акт терористичний.",
       "Справа серпня 31 (Заворушення масові серпня 31, Справа Конституції захисників) — провадження кримінальне, яке "
       "розслідується Поліцією національною, Безпеки службою та Прокуратурою генеральною України за фактом заворушень"
       " масових, поєднаних із нанесенням ушкоджень тілесних міліції працівникам та військовослужбовцям Гвардії "
       "національної України, а також смертей та поранень міліції працівників та військовослужбовців Національної "
       "України гвардії в результаті метання, за версією влади української, гранати РГО з натовпу в правоохоронців "
       "лаву, що було кваліфіковано як організований акт терористичний.",
       "Справа серпня 31 (Заворушення масові серпня 31, Справа Конституції захисників) — провадження кримінальне, яке "
       "розслідується Поліцією національною, Безпеки службою та Прокуратурою генеральною України за фактом заворушень"
       " масових, поєднаних із нанесенням ушкоджень тілесних міліції працівникам та військовослужбовцям Гвардії "
       "національної України, а також смертей та поранень міліції працівників та військовослужбовців Гвардії "
       "національної України в результаті метання, за версією влади української, гранати РГО з натовпу в правоохоронців"
       " лаву, що було кваліфіковано як організований акт терористичний."]],
     ["TP",
      [{'id': (1,), 'text': 'А', 'lemma': 'а', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 7, 'deprel': 'cc',
        'deps': '7:cc', 'misc': 'Id=16id|LTranslit=a|Translit=A'},
       {'id': (2,), 'text': 'там', 'lemma': 'там', 'upos': 'ADV', 'xpos': 'Pd------r', 'feats': 'PronType=Dem',
        'head': 7, 'deprel': 'advmod', 'deps': '7:advmod', 'misc': 'Id=16ie|LTranslit=tam|SpaceAfter=No|Translit=tam'},
       {'id': (3,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 5, 'deprel': 'punct',
        'deps': '5:punct', 'misc': 'Id=16if|LTranslit=,|Translit=,'},
       {'id': (4,), 'text': 'на', 'lemma': 'на', 'upos': 'ADP', 'xpos': 'Spsl', 'feats': 'Case=Loc', 'head': 5,
        'deprel': 'case', 'deps': '5:case', 'misc': 'Id=16ig|LTranslit=na|Translit=na'},
       {'id': (5,), 'text': 'землі', 'lemma': 'земля', 'upos': 'NOUN', 'xpos': 'Ncfsln',
        'feats': 'Animacy=Inan|Case=Loc|Gender=Fem|Number=Sing', 'head': 7, 'deprel': 'obl', 'deps': '7:obl',
        'misc': 'Id=16ih|LTranslit=zemľа|SpaceAfter=No|Translit=zemli'},
       {'id': (6,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 5, 'deprel': 'punct',
        'deps': '5:punct', 'misc': 'Id=16ii|LTranslit=,|Translit=,'},
       {'id': (7,), 'text': 'панує', 'lemma': 'панувати', 'upos': 'VERB', 'xpos': 'Vmpip3s',
        'feats': 'Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=16ij|LTranslit=panuvaty|Translit=panuě'},
       {'id': (8,), 'text': 'ясний', 'lemma': 'ясний', 'upos': 'ADJ', 'xpos': 'Afpmsnf',
        'feats': 'Case=Nom|Degree=Pos|Gender=Masc|Number=Sing', 'head': 9, 'deprel': 'amod', 'deps': '9:amod',
        'misc': 'Id=16ik|LTranslit=jasnyj|Translit=jasnyj'},
       {'id': (9,), 'text': 'спокій', 'lemma': 'спокій', 'upos': 'NOUN', 'xpos': 'Ncmsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Masc|Number=Sing', 'head': 7, 'deprel': 'nsubj', 'deps': '7:nsubj',
        'misc': 'Id=16il|LTranslit=spokij|SpaceAfter=No|Translit=spokij'},
       {'id': (10,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 14, 'deprel': 'punct',
        'deps': '14:punct', 'misc': 'Id=16im|LTranslit=,|Translit=,'},
       {'id': (11,), 'text': 'мрія', 'lemma': 'мрія', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 14, 'deprel': 'nsubj', 'deps': '14:nsubj',
        'misc': 'Id=16in|LTranslit=mrija|Translit=mrija'},
       {'id': (12,), 'text': 'ворога', 'lemma': 'ворог', 'upos': 'NOUN', 'xpos': 'Ncmsgy',
        'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing', 'head': 11, 'deprel': 'nmod', 'deps': '11:nmod',
        'misc': 'Id=16io|LTranslit=voroh|Translit=voroha'},
       {'id': (13,), 'text': 'мого', 'lemma': 'мій', 'upos': 'DET', 'xpos': 'Pps1m-sga',
        'feats': 'Case=Gen|Gender=Masc|Number=Sing|Person=1|Poss=Yes|PronType=Prs', 'head': 12, 'deprel': 'det',
        'deps': '12:det', 'misc': 'Id=16ip|LTranslit=mij|Translit=moho'},
       {'id': (14,), 'text': 'цвіте', 'lemma': 'цвісти', 'upos': 'VERB', 'xpos': 'Vmpip3s',
        'feats': 'Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'head': 7, 'deprel': 'parataxis',
        'deps': '7:parataxis', 'misc': 'Id=16iq|LTranslit=cvisty|Translit=cvite'},
       {'id': (15,), 'text': 'і', 'lemma': 'і', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 16, 'deprel': 'cc',
        'deps': '16:cc', 'misc': 'Id=16ir|LTranslit=i|Translit=i'},
       {'id': (16,), 'text': 'витає', 'lemma': 'витати', 'upos': 'VERB', 'xpos': 'Vmpip3s',
        'feats': 'Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'head': 14, 'deprel': 'conj',
        'deps': '14:conj', 'misc': 'Id=16is|LTranslit=vytaty|Translit=vytaě'},
       {'id': (17,), 'text': '—', 'lemma': '—', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Dash', 'head': 21,
        'deprel': 'punct', 'deps': '21:punct', 'misc': 'Id=16it|LTranslit=—|Translit=—'},
       {'id': (18,), 'text': 'і', 'lemma': 'і', 'upos': 'CCONJ', 'xpos': 'Ccs', 'head': 21, 'deprel': 'cc',
        'deps': '21:cc', 'misc': 'Id=16iu|LTranslit=i|Translit=i'},
       {'id': (19,), 'text': 'ніщо', 'lemma': 'ніщо', 'upos': 'PRON', 'xpos': 'Pz---n-nn',
        'feats': 'Animacy=Inan|Case=Nom|PronType=Neg', 'head': 21, 'deprel': 'nsubj', 'deps': '21:nsubj',
        'misc': 'Id=16iv|LTranslit=niščo|Translit=niščo'},
       {'id': (20,), 'text': 'не', 'lemma': 'не', 'upos': 'PART', 'xpos': 'Q', 'feats': 'Polarity=Neg', 'head': 21,
        'deprel': 'advmod', 'deps': '21:advmod', 'misc': 'Id=16iw|LTranslit=ne|Translit=ne'},
       {'id': (21,), 'text': 'бентежить', 'lemma': 'бентежити', 'upos': 'VERB', 'xpos': 'Vmpip3s',
        'feats': 'Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'head': 14, 'deprel': 'conj',
        'deps': '14:conj', 'misc': 'Id=16ix|LTranslit=bentežyty|Translit=bentežyť'},
       {'id': (22,), 'text': 'її', 'lemma': 'вона', 'upos': 'PRON', 'xpos': 'Pp-3f-san',
        'feats': 'Case=Acc|Gender=Fem|Number=Sing|Person=3|PronType=Prs', 'head': 21, 'deprel': 'obj', 'deps': '21:obj',
        'misc': 'Id=16iy|LTranslit=vona|SpaceAfter=No|Translit=jiji'},
       {'id': (23,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 7, 'deprel': 'punct',
        'deps': '7:punct', 'misc': 'Id=16iz|LTranslit=.|Translit=.'}],
      ["А там, на землі, панує спокій ясний, мрія ворога мого цвіте і витає — і ніщо не бентежить її."]],
     ["TP",
      [{'id': (1,), 'text': 'У', 'lemma': 'у', 'upos': 'ADP', 'xpos': 'Spsl', 'feats': 'Case=Loc', 'head': 3,
        'deprel': 'case', 'deps': '3:case', 'misc': 'Id=1z40|LTranslit=u|Translit=U'},
       {'id': (2,), 'text': 'генеральному', 'lemma': 'генеральний', 'upos': 'ADJ', 'xpos': 'Ao-mslf',
        'feats': 'Case=Loc|Gender=Masc|Number=Sing', 'head': 3, 'deprel': 'amod', 'deps': '3:amod',
        'misc': 'Id=1z41|LTranslit=heneraľnyj|Translit=heneraľnomu'},
       {'id': (3,), 'text': 'плані', 'lemma': 'план', 'upos': 'NOUN', 'xpos': 'Ncmsln',
        'feats': 'Animacy=Inan|Case=Loc|Gender=Masc|Number=Sing', 'head': 22, 'deprel': 'obl', 'deps': '22:obl',
        'misc': 'Id=1z42|LTranslit=plan|Translit=plani'},
       {'id': (4,), 'text': 'міста', 'lemma': 'місто', 'upos': 'NOUN', 'xpos': 'Ncnsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Neut|Number=Sing', 'head': 3, 'deprel': 'nmod', 'deps': '3:nmod',
        'misc': 'Id=1z43|LTranslit=misto|Translit=mista'},
       {'id': (5,), 'text': 'територія', 'lemma': 'територія', 'upos': 'NOUN', 'xpos': 'Ncfsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 22, 'deprel': 'nsubj',
        'deps': '18:obl:rel|22:nsubj', 'misc': 'Id=1z44|LTranslit=terytorija|SpaceAfter=No|Translit=terytorija'},
       {'id': (6,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 18, 'deprel': 'punct',
        'deps': '18:punct', 'misc': 'Id=1z45|LTranslit=,|Translit=,'},
       {'id': (7,), 'text': 'на', 'lemma': 'на', 'upos': 'ADP', 'xpos': 'Spsl', 'feats': 'Case=Loc', 'head': 8,
        'deprel': 'case', 'deps': '8:case', 'misc': 'Id=1z46|LTranslit=na|Translit=na'},
       {'id': (8,), 'text': 'якій', 'lemma': 'який', 'upos': 'DET', 'xpos': 'Pr--f-sla',
        'feats': 'Case=Loc|Gender=Fem|Number=Sing|PronType=Rel', 'head': 18, 'deprel': 'obl', 'deps': '5:ref|18:obl',
        'misc': 'Id=1z47|LTranslit=jakyj|Translit=jakij'},
       {'id': (9,), 'text': 'орендар', 'lemma': 'орендар', 'upos': 'NOUN', 'xpos': 'Ncmsny',
        'feats': 'Animacy=Anim|Case=Nom|Gender=Masc|Number=Sing', 'head': 18, 'deprel': 'nsubj', 'deps': '18:nsubj',
        'misc': 'Id=1z48|LTranslit=orendar|Translit=orendar'},
       {'id': (10,), 'text': '–', 'lemma': '–', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Dash', 'head': 11,
        'deprel': 'punct', 'deps': '11:punct', 'misc': 'Id=1z49|LTranslit=–|Translit=–'},
       {'id': (11,), 'text': 'ТОВ', 'lemma': 'ТОВ', 'upos': 'NOUN', 'xpos': 'Y',
        'feats': 'Abbr=Yes|Animacy=Inan|Case=Nom|Gender=Neut|Number=Sing|Uninflect=Yes', 'head': 9, 'deprel': 'appos',
        'deps': '9:appos', 'misc': 'Id=1z4a|LTranslit=TOV|Translit=TOV'},
       {'id': (12,), 'text': '“', 'lemma': '“', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Quot', 'head': 15,
        'deprel': 'punct', 'deps': '15:punct', 'misc': 'Id=1z4b|LTranslit=“|SpaceAfter=No|Translit=“'},
       {'id': (13,), 'text': 'Київщина', 'lemma': 'Київщина', 'upos': 'PROPN', 'xpos': 'Npfsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing', 'head': 15, 'deprel': 'compound',
        'deps': '15:compound', 'misc': 'Id=1z4c|LTranslit=Kyjivščyna|SpaceAfter=No|Translit=Kyjivščyna'},
       {'id': (14,), 'text': '-', 'lemma': '-', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Hyph', 'head': 13,
        'deprel': 'punct', 'deps': '13:punct', 'misc': 'Id=1z4d|LTranslit=-|SpaceAfter=No|Translit=-'},
       {'id': (15,), 'text': 'Житло', 'lemma': 'житло', 'upos': 'NOUN', 'xpos': 'Ncnsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Neut|Number=Sing', 'head': 11, 'deprel': 'flat:title',
        'deps': '11:flat:title', 'misc': 'Id=1z4e|LTranslit=žytlo|SpaceAfter=No|Translit=Žytlo'},
       {'id': (16,), 'text': '”', 'lemma': '”', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Quot', 'head': 15,
        'deprel': 'punct', 'deps': '15:punct', 'misc': 'Id=1z4f|LTranslit=”|Translit=”'},
       {'id': (17,), 'text': '–', 'lemma': '–', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Dash', 'head': 11,
        'deprel': 'punct', 'deps': '11:punct', 'misc': 'Id=1z4g|LTranslit=–|Translit=–'},
       {'id': (18,), 'text': 'зводитиме', 'lemma': 'зводити', 'upos': 'VERB', 'xpos': 'Vmpif3s',
        'feats': 'Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Fut|VerbForm=Fin', 'head': 5, 'deprel': 'acl:relcl',
        'deps': '5:acl:relcl', 'misc': 'Id=1z4h|LTranslit=zvodyty|Translit=zvodytyme'},
       {'id': (19,), 'text': 'багатоповерхівки', 'lemma': 'багатоповерхівка', 'upos': 'NOUN', 'xpos': 'Ncfpan',
        'feats': 'Animacy=Inan|Case=Acc|Gender=Fem|Number=Plur', 'head': 18, 'deprel': 'obj', 'deps': '18:obj',
        'misc': 'Id=1z4i|LTranslit=bahatopoverchivka|SpaceAfter=No|Translit=bahatopoverchivky'},
       {'id': (20,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 18, 'deprel': 'punct',
        'deps': '18:punct', 'misc': 'Id=1z4j|LTranslit=,|Translit=,'},
       {'id': (21,), 'text': 'досі', 'lemma': 'досі', 'upos': 'ADV', 'xpos': 'Pd------r', 'feats': 'PronType=Dem',
        'head': 22, 'deprel': 'advmod', 'deps': '22:advmod', 'misc': 'Id=1z4k|LTranslit=dosi|Translit=dosi'},
       {'id': (22,), 'text': 'позначена', 'lemma': 'позначений', 'upos': 'ADJ', 'xpos': 'Ap-fsns-ep',
        'feats': 'Aspect=Perf|Case=Nom|Gender=Fem|Number=Sing|VerbForm=Part|Voice=Pass', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=1z4l|LTranslit=poznačenyj|Translit=poznačena'},
       {'id': (23,), 'text': 'як', 'lemma': 'як', 'upos': 'SCONJ', 'xpos': 'Css', 'head': 25, 'deprel': 'mark',
        'deps': '25:mark', 'misc': 'Id=1z4m|LTranslit=jak|Translit=jak'},
       {'id': (24,), 'text': '«', 'lemma': '«', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Quot', 'head': 25,
        'deprel': 'punct', 'deps': '25:punct', 'misc': 'Id=1z4n|LTranslit=«|SpaceAfter=No|Translit=«'},
       {'id': (25,), 'text': 'ліси', 'lemma': 'ліс', 'upos': 'NOUN', 'xpos': 'Ncmpnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Masc|Number=Plur', 'head': 22, 'deprel': 'advcl', 'deps': '22:advcl',
        'misc': 'Id=1z4o|LTranslit=lis|SpaceAfter=No|Translit=lisy'},
       {'id': (26,), 'text': '»', 'lemma': '»', 'upos': 'PUNCT', 'xpos': 'U', 'feats': 'PunctType=Quot', 'head': 25,
        'deprel': 'punct', 'deps': '25:punct', 'misc': 'Id=1z4p|LTranslit=»|SpaceAfter=No|Translit=»'},
       {'id': (27,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 31, 'deprel': 'punct',
        'deps': '31:punct', 'misc': 'Id=1z4q|LTranslit=,|Translit=,'},
       {'id': (28,), 'text': 'цей', 'lemma': 'цей', 'upos': 'DET', 'xpos': 'Pd--m-sna',
        'feats': 'Case=Nom|Gender=Masc|Number=Sing|PronType=Dem', 'head': 29, 'deprel': 'det', 'deps': '29:det',
        'misc': 'Id=1z4r|LTranslit=cej|Translit=cej'},
       {'id': (29,), 'text': 'план', 'lemma': 'план', 'upos': 'NOUN', 'xpos': 'Ncmsnn',
        'feats': 'Animacy=Inan|Case=Nom|Gender=Masc|Number=Sing', 'head': 31, 'deprel': 'nsubj', 'deps': '31:nsubj',
        'misc': 'Id=1z4s|LTranslit=plan|Translit=plan'},
       {'id': (30,), 'text': 'не', 'lemma': 'не', 'upos': 'PART', 'xpos': 'Q', 'feats': 'Polarity=Neg', 'head': 31,
        'deprel': 'advmod', 'deps': '31:advmod', 'misc': 'Id=1z4t|LTranslit=ne|Translit=ne'},
       {'id': (31,), 'text': 'змінювався', 'lemma': 'змінюватися', 'upos': 'VERB', 'xpos': 'Vmpis-sm',
        'feats': 'Aspect=Imp|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 22,
        'deprel': 'parataxis', 'deps': '22:parataxis', 'misc': 'Id=1z4u|LTranslit=zmińuvatyśа|Translit=zmińuvavśа'},
       {'id': (32,), 'text': 'роками', 'lemma': 'роками', 'upos': 'ADV', 'xpos': 'R', 'head': 31, 'deprel': 'advmod',
        'deps': '31:advmod', 'misc': 'Id=1z4v|LTranslit=rokamy|SpaceAfter=No|Translit=rokamy'},
       {'id': (33,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 22, 'deprel': 'punct',
        'deps': '22:punct', 'misc': 'Id=1z4w|LTranslit=.|Translit=.'}],
      ["У генеральному міста плані територія, на якій орендар – ТОВ “Київщина-Житло” – багатоповерхівки зводитиме,"
       " досі позначена як «ліси», цей план не змінювався роками.",
       "У плані генеральному міста територія, на якій орендар – ТОВ “Київщина-Житло” – багатоповерхівки зводитиме, "
       "досі позначена як «ліси», цей план не змінювався роками."]],
     ["TP",
      [{'id': (1,), 'text': '2007-го', 'lemma': '2007-ий', 'upos': 'NOUN', 'xpos': 'Ao-msgf',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 2, 'deprel': 'obl', 'deps': '2:obl',
        'misc': 'Id=1w88|LTranslit=2007-yj|Translit=2007-ho'},
       {'id': (2,), 'text': 'здобув', 'lemma': 'здобути', 'upos': 'VERB', 'xpos': 'Vmeis-sm',
        'feats': 'Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=1w89|LTranslit=zdobuty|Translit=zdobuv'},
       {'id': (3,), 'text': 'ступінь', 'lemma': 'ступінь', 'upos': 'NOUN', 'xpos': 'Ncmsan',
        'feats': 'Animacy=Inan|Case=Acc|Gender=Masc|Number=Sing', 'head': 2, 'deprel': 'obj', 'deps': '2:obj',
        'misc': 'Id=1w8a|LTranslit=stupiń|Translit=stupiń'},
       {'id': (4,), 'text': 'магістра', 'lemma': 'магістр', 'upos': 'NOUN', 'xpos': 'Ncmsgy',
        'feats': 'Animacy=Anim|Case=Gen|Gender=Masc|Number=Sing', 'head': 3, 'deprel': 'nmod', 'deps': '3:nmod',
        'misc': 'Id=1w8b|LTranslit=mahistr|Translit=mahistra'},
       {'id': (5,), 'text': 'політичних', 'lemma': 'політичний', 'upos': 'ADJ', 'xpos': 'Ao--pgf',
        'feats': 'Case=Gen|Number=Plur', 'head': 6, 'deprel': 'amod', 'deps': '6:amod',
        'misc': 'Id=1w8c|LTranslit=polityčnyj|Translit=polityčnych'},
       {'id': (6,), 'text': 'наук', 'lemma': 'наука', 'upos': 'NOUN', 'xpos': 'Ncfpgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Fem|Number=Plur', 'head': 4, 'deprel': 'nmod', 'deps': '4:nmod',
        'misc': 'Id=1w8d|LTranslit=nauka|Translit=nauk'},
       {'id': (7,), 'text': 'того', 'lemma': 'той', 'upos': 'DET', 'xpos': 'Pd--m-sga',
        'feats': 'Case=Gen|Gender=Masc|Number=Sing|PronType=Dem', 'head': 9, 'deprel': 'det', 'deps': '9:det',
        'misc': 'Id=1w8e|LTranslit=toj|Translit=toho'},
       {'id': (8,), 'text': 'самого', 'lemma': 'самий', 'upos': 'DET', 'xpos': 'Px--m-sga',
        'feats': 'Case=Gen|Gender=Masc|Number=Sing|PronType=Prs|Reflex=Yes', 'head': 9, 'deprel': 'det',
        'deps': '9:det', 'misc': 'Id=1w8f|LTranslit=samyj|Translit=samoho'},
       {'id': (9,), 'text': 'вишу', 'lemma': 'виш', 'upos': 'NOUN', 'xpos': 'Ncmsgn',
        'feats': 'Animacy=Inan|Case=Gen|Gender=Masc|Number=Sing', 'head': 4, 'deprel': 'nmod', 'deps': '4:nmod',
        'misc': 'Id=1w8g|LTranslit=vyš|SpaceAfter=No|Translit=vyšu'},
       {'id': (10,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 2, 'deprel': 'punct',
        'deps': '2:punct', 'misc': 'Id=1w8h|LTranslit=.|Translit=.'}],
      ["Здобув 2007-го ступінь магістра наук політичних того самого вишу."]],
     ["TP",
      [{'id': (1,), 'text': 'Я', 'lemma': 'я', 'upos': 'PRON', 'xpos': 'Pp-1-ysnn',
        'feats': 'Animacy=Anim|Case=Nom|Number=Sing|Person=1|PronType=Prs', 'head': 2, 'deprel': 'nsubj',
        'deps': '2:nsubj', 'misc': 'Id=0sei|LTranslit=ja|Translit=Ja'},
       {'id': (2,), 'text': 'уявляв', 'lemma': 'уявляти', 'upos': 'VERB', 'xpos': 'Vmpis-sm',
        'feats': 'Aspect=Imp|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin', 'head': 0, 'deprel': 'root',
        'deps': '0:root', 'misc': 'Id=0sej|LTranslit=ujavľаty|Translit=ujavľаv'},
       {'id': (3,), 'text': 'собі', 'lemma': 'себе', 'upos': 'PRON', 'xpos': 'Px-----dn',
        'feats': 'Case=Dat|PronType=Prs|Reflex=Yes', 'head': 2, 'deprel': 'expl', 'deps': '2:expl',
        'misc': 'Id=0sek|LTranslit=sebe|SpaceAfter=No|Translit=sobi'},
       {'id': (4,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 6, 'deprel': 'punct',
        'deps': '6:punct', 'misc': 'Id=0sel|LTranslit=,|Translit=,'},
       {'id': (5,), 'text': 'що', 'lemma': 'що', 'upos': 'PRON', 'xpos': 'Pr--nnsan',
        'feats': 'Animacy=Inan|Case=Acc|Gender=Neut|Number=Sing|PronType=Rel', 'head': 6, 'deprel': 'obj',
        'deps': '6:obj', 'misc': 'Id=0sem|LTranslit=ščo|Translit=ščo'},
       {'id': (6,), 'text': 'переживають', 'lemma': 'переживати', 'upos': 'VERB', 'xpos': 'Vmpip3p',
        'feats': 'Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'head': 2, 'deprel': 'ccomp',
        'deps': '2:ccomp', 'misc': 'Id=0sen|LTranslit=perežyvaty|Translit=perežyvajuť'},
       {'id': (7,), 'text': 'померлі', 'lemma': 'померлі', 'upos': 'NOUN', 'xpos': 'Ap--pns-',
        'feats': 'Animacy=Anim|Case=Nom|Number=Ptan', 'head': 6, 'deprel': 'nsubj', 'deps': '6:nsubj',
        'misc': 'Id=0seo|LTranslit=pomerli|SpaceAfter=No|Translit=pomerli'},
       {'id': (8,), 'text': ',', 'lemma': ',', 'upos': 'PUNCT', 'xpos': 'U', 'head': 9, 'deprel': 'punct',
        'deps': '9:punct', 'misc': 'Id=0sep|LTranslit=,|Translit=,'},
       {'id': (9,), 'text': 'чекаючи', 'lemma': 'чекати', 'upos': 'VERB', 'xpos': 'Vmpgp',
        'feats': 'Aspect=Imp|Tense=Pres|VerbForm=Conv', 'head': 6, 'deprel': 'advcl', 'deps': '6:advcl',
        'misc': 'Id=0seq|LTranslit=čekaty|Translit=čekajučy'},
       {'id': (10,), 'text': 'на', 'lemma': 'на', 'upos': 'ADP', 'xpos': 'Spsa', 'feats': 'Case=Acc', 'head': 11,
        'deprel': 'case', 'deps': '11:case', 'misc': 'Id=0ser|LTranslit=na|Translit=na'},
       {'id': (11,), 'text': 'нас', 'lemma': 'ми', 'upos': 'PRON', 'xpos': 'Pp-1-ypan',
        'feats': 'Animacy=Anim|Case=Acc|Number=Plur|Person=1|PronType=Prs', 'head': 9, 'deprel': 'obl', 'deps': '9:obl',
        'misc': 'Id=0ses|LTranslit=my|SpaceAfter=No|Translit=nas'},
       {'id': (12,), 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'U', 'head': 2, 'deprel': 'punct',
        'deps': '2:punct', 'misc': 'Id=0set|LTranslit=.|Translit=.'}],
      ["Уявляв я собі, що померлі переживають, чекаючи на нас."]]
    ])
    def test_ud_augment(self, name, doc, expected):
        doc_to_aug = DataAugmentation(doc)
        doc_to_aug.augment()
        aug_sents = doc_to_aug.get_aug_docs()
        actual = [doc_to_text(aug_s) for aug_s in aug_sents]
        print(actual)
        print(len(actual))
        assert_equal(actual, expected)